### ISSUE TITLE
Codex GUI at different resolutions

### ISSUE THREAD

**Issue by Astebrooke** [TeamWizardry/Wizardry#100]
The GUI looks (mostly) fine windowed, as can be seen below.
![2018-01-25_16 46 50](https://user-images.githubusercontent.com/35822449/35420898-ee5abe4a-01f4-11e8-835b-af9a324d7093.png)

However, while the content scales, the preview window does not.  When my game is full screen this is what the same page looks like.
![2018-01-25_16 46 54](https://user-images.githubusercontent.com/35822449/35420920-10f4ff60-01f5-11e8-87b1-1caa9536407a.png)

Also note the transparency in the Materials bookmark in both screenshots, which makes it almost impossible to read against some backdrops.

I'm guessing the window that the structural preview is shown in has specific dimensions instead of dynamic?

**Comment by SilkenStrand** [comment]
Oh damn thanks for showing me What Causes This so I can at least work around it. Hope it's fixed soon - I do prefer playing with the window maximized...

(so on a more relevant note - +1 confirm, this isn't just you)

**Comment by Demoniaque** [comment]
Whole book got overhauled in 0.8. Should be fixed.
