### ISSUE TITLE
There are problems in Chinese translation

### ISSUE THREAD

**Issue by forestbat** [TeamWizardry/Wizardry#105]
I added zh_cn.json in PR #102 ，but in game I can't see Chinese。
![2018-02-16_17 05 44](https://user-images.githubusercontent.com/23413915/36300454-5196a30e-133c-11e8-8fd3-24f6514c482e.png)

**Comment by murapix** [comment]
Yes, this update cycle's been really slow, due to both of us having other things we needed to do over Wizardry. Demoniaque is making some changes to the book, and once those are done, we'll be pushing out the update that contains your PR.

**Comment by forestbat** [comment]
OK thanks。
