### ISSUE TITLE
Strange, server-sided crash

### ISSUE THREAD

**Issue by Sunconure11** [TeamWizardry/Wizardry#107]
https://pastebin.com/NjqDHv6W

Resetting the map did not stop this. The dimension ID for the underworld is currently set to 42. It seemingly triggered after I switched some of the flags so I'm using G1GC garbage cleaning.

**Comment by Demoniaque** [comment]
You have another mod using dimension Id 33?

**Comment by Sunconure11** [comment]
No, not that I'm aware of. The issue seemed to go away when I pruned my args.
