### ISSUE TITLE
Client crash when casting spell- projectile reinforcements

### ISSUE THREAD

**Issue by ProsperCraft** [TeamWizardry/Wizardry#108]
https://gist.github.com/ProsperCraft/8c884f8bedf509d6fef73f4a1ff6a4f5

Reproduced here -

https://gist.github.com/ProsperCraft/1b253ae033bde6e36bc68885965e5126

**Comment by Demoniaque** [comment]
wawla bug. We fixed it in the next update which will be out soon. Remove
wawla for now.

**Comment by ProsperCraft** [comment]
Switched to oneprobe works around it for now.

**Comment by murapix** [comment]
Update went out that contained the fix
