### ISSUE TITLE
Possible conflict with Terraqueous?

### ISSUE THREAD

**Issue by faeldray** [TeamWizardry/Wizardry#111]
I've been playing fine in my world for quite a while now, but as I was exploring a jungle, I suddenly crashed with the following error: https://pastebin.com/bf4nnKcD

**Comment by pau101** [comment]
Thanks for the report! This is an issue in Terraqueous which can be reported to them here https://github.com/ShetiPhian/Localizations-and-Issues/issues

**Comment by Demoniaque** [comment]
Thank you, Paul.

**Comment by faeldray** [comment]
Thanks for the speedy response, I'll put in a ticket with them right away.
