### ISSUE TITLE
Update message lacks localization

### ISSUE THREAD

**Issue by Sunconure11** [TeamWizardry/Wizardry#113]
On build 0.8, it would seem the update message lacks localization. This issue is minor, but it was obviously overlooked.

**Comment by yrsegal** [comment]
If you're talking about [this](https://github.com/TeamWizardry/Wizardry/blob/master/src/main/java/com/teamwizardry/wizardry/common/core/version/ThreadVersionChecker.java#L47), that's intended. Log text doesn't get localized for the most part.
If you're talking about [this](https://github.com/TeamWizardry/Wizardry/blob/master/src/main/java/com/teamwizardry/wizardry/common/core/version/VersionChecker.java#L41-L76), look at all the plaintext I do not see.
