### ISSUE TITLE
Versions -0.8 crash 

### ISSUE THREAD

**Issue by knoxhack** [TeamWizardry/Wizardry#114]
librarianlib version: 1.12.2-4.8

https://gist.github.com/knoxhack/5013690855d4b495cfadfc217624986e

**Comment by knoxhack** [comment]
this is a server crash

**Comment by yrsegal** [comment]
Solved by https://github.com/TeamWizardry/Wizardry/commit/b017ce5d1bf54b34518d6483e66089deba76f10b, update shortly

**Comment by murapix** [comment]
Update is currently on Curse, you should be good to go.
