### ISSUE TITLE
Golden nugget in to mana liquide crash

### ISSUE THREAD

**Issue by mandonnaud** [TeamWizardry/Wizardry#117]
Version 0.8.2

Crash : Gold nugget in to mana liquide

Crash solo and multi

Crash multi :
https://pastebin.com/JwqGPcsC

Crash solo : 
https://pastebin.com/6V4YCTHy

**Comment by Serifina** [comment]
Same here.

https://pastebin.com/ZD1AAgea

**Comment by murapix** [comment]
Currently testing fixes to this, and other bugs. If all goes well, there'll be an update out later today.

**Comment by Serifina** [comment]
Awesome. Thanks!

**Comment by xAlicatt** [comment]
I was coming here to report this. So I'm going to guess it was fixed in the newest update then?

**Comment by murapix** [comment]
Looks like the fix was a success, so yes, it is fixed as of 0.8.3.
