### ISSUE TITLE
Mana pools in explored chunks dissapeared after upgrade from 0.82 to 0.85

### ISSUE THREAD

**Issue by ibekimc** [TeamWizardry/Wizardry#123]
There were several mana pools around our explored areas, after the update from 0.82 to 0.85 all of them were empty upon visiting. The Journey Map showed the mana pools but once you entered the area the map was updated to show only the depression where the pool had been.

Upon further exploration and finally creating new chunks, I was able to find a couple of new mana pools. So it does seem limited to the upgrade process.

**Comment by Demoniaque** [comment]
No clue. Mod is in alpha, plenty of warnings. We probably changed the mana back then.
