### ISSUE TITLE
Selecting search result in Manual causes game crash

### ISSUE THREAD

**Issue by ibekimc** [TeamWizardry/Wizardry#124]
When searching for Mana and then clicking on one of the results game crashes.

Crash report attached.

[crash-2018-04-15_21.57.47-client.txt](https://github.com/TeamWizardry/Wizardry/files/1913938/crash-2018-04-15_21.57.47-client.txt)

**Comment by murapix** [comment]
This looks like a LibLib issue, pointing it towards the guy who worked on that part.

**Comment by Demoniaque** [comment]
probably fixed? @yrsegal pls confirm
