### ISSUE TITLE
Caught Java exception from wizardry (Wizardry) with Sponge-Forge API

### ISSUE THREAD

**Issue by Thanatosus** [TeamWizardry/Wizardry#125]
Hello,

I'm making a magic mod pack, and today after testing the mod on my local machine everything was fine, but adding it on the server with Sponge-Forge result in a fatal error.

The error was detected in PREINITIALIZATION step.

Hope this information will be useful for you.

I'm using the recommended build of Forge 1.12 (14.23.3.2655) and 7.1.0-BETA-3025 build of Sponge.
I put the error stack in the attached files.

Hope those information could help to improve the mod.

Have a nice day and thank you very much for your nice work.

Thanatosus

PS: 
Server launch log:
[latest.log](https://github.com/TeamWizardry/Wizardry/files/1917276/latest.log)

Debug log:
[debug.log](https://github.com/TeamWizardry/Wizardry/files/1917282/debug.log)

**Comment by Thanatosus** [comment]
Re-Hello,

A friend of mine just had a look on the error stack and make me launch that command:

sudo apt-get install **libxrender1 libxtst6 libxi6**

and that helped.

I think that (maybe) on the Ubuntu Server 16.04 LTS there are not all the libraries which was installed from the beginning and so you need to install them manually after the Java installation -.- 

So the server has launched and generated a fresh map and a fresh config folders.

But now I have a strange behaviour. After launching the "/wizardry reset" command I have a "FMLIndexedMessageCodec exception " with a huge error stack, BUT the server is continuing to work. 

I'm afraid that this might crush the server further if people will use Wizardry items and mechanics.

I put a new error stack here (in latest.log error begin from line 1431)
[latest.log](https://github.com/TeamWizardry/Wizardry/files/1917514/latest.log)

And a debug file (error begins from 18397 line):
[debug.log](https://github.com/TeamWizardry/Wizardry/files/1917517/debug.log)

Is that a normal behaviour ?

**Comment by Demoniaque** [comment]
I got no clue. Update everything possible in ubuntu.
