### ISSUE TITLE
Glass Orbs in a Mana Pool not Becoming Mana Orbs

### ISSUE THREAD

**Issue by FallenEagle1** [TeamWizardry/Wizardry#126]
Modpack: All the Mods 3 5.9.3 and 5.9.3b
Mod Version: 0.8.5
Forge: 14.23.2.2654

This bug was found in the ATM3 modpack, but when tested with just wizardry and jei, I was unable to reproduce it.

The bug found is when a glass orb is thrown into a pool of mana of any size, it will not convert into a mana orb and fill up. The particle effects do show up while the orb is in the water, but nothing else changes. If a partially filled mana orb is thrown into the pool, it will fill up properly. Nothing significant was found in the logs to indicate what the possible issue may be, but they can be provided if you want them.

**Comment by murapix** [comment]
Actually, could you provide the contents of the config/wizardry/fluid_recipes folder (specifically the mana orb one)?

**Comment by FallenEagle1** [comment]
Sure thing. Its the whole folder since github doesn't like .jsons for upload. If you want, I could go through and try finding if it is a mod conflict. 
[fluid_recipes.zip](https://github.com/TeamWizardry/Wizardry/files/1926558/fluid_recipes.zip)

**Comment by murapix** [comment]
Is this from when it was just Wizardry and JEI, or from the ATM3 pack? I need the one that didn't work to make sure.

**Comment by FallenEagle1** [comment]
That folder was from the modpack variant. I was thinking it is some sort of mod interaction, but wanted to double check before picking the pack apart.

**Comment by murapix** [comment]
Sounds like it might be a mod interaction then, since that recipe looks correct. To make sure though, could you delete that recipes folder then restart the pack?

**Comment by FallenEagle1** [comment]
Just tested and it is working now. Deleted them and it reset the config folder. I'll relay this to the ATM devs.
