### ISSUE TITLE
Illumination spell causing unremovable particles

### ISSUE THREAD

**Issue by Sonicx32** [TeamWizardry/Wizardry#128]
Crafted a basic projectile -> Illumination spell and on right click it creates a large green orb of particles which rain down smaller particles. Orbs seem to be irremovable by all conventional means. I have tried placing fluids over the light, placing blocks on the light, breaking the light with bare hands and staff. Nothing works. How do i remove these???

**Comment by Demoniaque** [comment]
If you can't break them, then there's a client/server desync. Relog.
