### ISSUE TITLE
Magician's Worktable causes the game to completely stop

### ISSUE THREAD

**Issue by q3AEWRSDTFGYHUJNKMIHUGBTYRFDYSIYGUH** [TeamWizardry/Wizardry#130]
When I try to make a spell in the Magician's Worktable, my game freezes. The launcher's log says that it's running a few thousand milliseconds behind, fluctuating from 4000 to 10000. I don't know what causes this.

**Comment by Demoniaque** [comment]
We can't know either without more detail
