### ISSUE TITLE
TPS lag buildup

### ISSUE THREAD

**Issue by ouroborus** [TeamWizardry/Wizardry#136]
It seems that Wizardy eats more and more processing time when handling its active tiles.

I've observed (via LagGoggles) the active tiles involved in a mana battery and a crafting plate multiblock structure eat more and more processing time. This seems to happen when a nearby, unrelated spawner-based farm is actively generating/killing critters. I don't know if or why these would be related but it's clear that, when the farm is on, active Wizardry tiles take longer and longer to process.

This screenshot shows timings after having been running for about 8 hours. Total processing time for just Wizardry in this screenshot averages ~46ms/t over a 60 second period. The budget for all processing in Minecraft is 50ms/t. 
![2018-05-14_09 04 32](https://user-images.githubusercontent.com/392047/40009194-37488054-5756-11e8-8682-ff10ae85f316.png)

**Comment by Demoniaque** [comment]
This is due to them continuously checking their surroundings unfortunately. will have to see if I can run soft updates when a block update happens or something

**Comment by ouroborus** [comment]
Out of curiosity, aside from structure, what are they checking for? It seems odd that this checking takes longer and longer over time under certain conditions.

**Comment by Demoniaque** [comment]
They all constantly check for each other's Mana levels to equalize the whole Mana network at any imbalance

**Comment by Demoniaque** [comment]
Added to TODO for 0.9.3 or .4

**Comment by Demoniaque** [comment]
So, after a bit of tweaking and testing, this is the new result from lagGoggles:
https://i.imgur.com/9uE9Rj4.png

Ticking is down by ~3000% since your last lagGoggles result.

It was a matter of several small optimizations.
