### ISSUE TITLE
Crash while booting a game

### ISSUE THREAD

**Issue by Sunconure11** [TeamWizardry/Wizardry#137]
https://pastebin.com/AryzqRvm

Possibly related to this:

https://github.com/DimensionalDevelopment/VanillaFix/issues/19

**Comment by Runemoro** [comment]
Thanks for the report, I'll fix this for next release. The animation optimization has to be adjusted to be compatible with a few mods apparently.

**Comment by Runemoro** [comment]
This is caused by VanillaFix, wizardry is calling BlockModelRenderer directly, which VanillaFix did not expect. It will be fixed in VanillaFix 1.0.4.
