### ISSUE TITLE
Creating Real Halo from Crude Halo

### ISSUE THREAD

**Issue by shadowfoxx89** [TeamWizardry/Wizardry#140]
I'm having trouble creating the Real Halo out of the recipe shown in the JEI . Wondering if it isn't completed yet or just bugged.

**Comment by murapix** [comment]
Could you give more info about what you're doing? The recipe works fine on our end.

**Comment by shadowfoxx89** [comment]
Recipe shows to add Crude Halo along with Prismarine Shard, Nether Star, Dragon's Breath, Fairy Dust, Devil Dust and Unicorn Horn into a Mana Pool. I do that and get the reaction from the pool, but nothing seems to happen.

**Comment by shadowfoxx89** [comment]
Nevermind my mistake. I was missing 5 source blocks of Mana XD

**Comment by murapix** [comment]
Glad to hear you figured it out
