### ISSUE TITLE
[ATM3 5.95] Leaving Underworld in Multiplayer instantly kills you

### ISSUE THREAD

**Issue by murapix** [TeamWizardry/Wizardry#141]
Seems to be a server-only thing, as last reporter of this issue noted:

`so i was playing on a private server with some friends when it happened originally, and now i tried it on a singleplayer world, and i didnt die, so theres another possible cause?`

**Comment by kreezxil** [comment]
confirmed this has happened to one of my players. He did it twice in a 10 minute period dieing both times.
There are no server crash reports except for these logs.

## Details:
Minecraft Version: 1.12.2-14.23.5.2772
Modpack: World of Dragons Ultra Lite (WOD) **I am the dev of this pack**
Modpack Version: 1.3.4
Modpack Mods: http://paste.ubuntu.com/p/DZ9PH7KH25/

## debug.log
http://paste.ubuntu.com/p/HyMQjN2XKC/

## latest.log
http://paste.ubuntu.com/p/RxQ9B6PYJD/

**Comment by SwissCheese5** [comment]
Should be fixed by now.
