### ISSUE TITLE
0.8.5 Version checker issues 

### ISSUE THREAD

**Issue by ProsperCraft** [TeamWizardry/Wizardry#143]
1. The version checker doesn't obey B:version_checker_enabled=false,

2. I have the latest version, yet the log still says I need to update.  [Wizardry Version Checker Thread/ERROR] [wizardry]: New version found! -> 0.8.5

Log attached.
[2018-06-18-2.log](https://github.com/TeamWizardry/Wizardry/files/2128169/2018-06-18-2.log)

**Comment by Demoniaque** [comment]
Tell me if this is fixed in 0.9.x please.
