### ISSUE TITLE
Invalid nacre time with dynamic tick rate?

### ISSUE THREAD

**Issue by sum-catnip** [TeamWizardry/Wizardry#145]
Is it possible that the nacre quality calculation doesn't use real time but mc ticks? because i have tick dynamic installed and the 30 seconds are completely off. i also took a look at the code (INacreProduct.java seems to be the relevant file) and it does not look like its using real time.

**Comment by murapix** [comment]
Yes, it assumes the standard 20 ticks per second, and has a duration of 600 ticks required for a perfect pearl.

**Comment by sum-catnip** [comment]
wouldn't it be better to measure the 30 seconds in real time rather than ticks? Because with mods like tick dynamic it becomes pretty unpredictable. Or is it just not smart to change the tick rate?

**Comment by yrsegal** [comment]
Not smart to change the tick rate. 

We don't *have* any way to measure real time... would you have us measure it on server? On client? How would we decide what's the "correct" place to measure?
Ticks are supposed to be 20 per second, and messing with that is going to mess with all timing, everywhere.
