### ISSUE TITLE
Crash When Opening Book after Creating Spell

### ISSUE THREAD

**Issue by TechnoMysterio** [TeamWizardry/Wizardry#146]
I attempted to make a simple projectile frost spell while testing the mod in creative mod. I set up and connected the components, and then I saved the spell. After this, I tried to open to book to look at the spell ingredients, and the game crashed. Crashlog:

https://paste.dimdev.org/cequgegave.mccrash

Wizardry: 0.9.0
librarianlib: 1.12.2-4.9
Forgelin: 1.7.4
MC Forge: 14.23.4.2739

**Comment by Demoniaque** [comment]
This is because liblib hasn't updated yet to 4.10. Please give them a day or two and they should have an update out.
