### ISSUE TITLE
Server-side crash on version 0.9.0

### ISSUE THREAD

**Issue by belathus** [TeamWizardry/Wizardry#147]
https://gist.github.com/belathus/63c3767d820747b7c3fafcd8c6ebc8b6

Looks like it is trying to render something on a headless server.

**Comment by netcore10** [comment]
i get this too

**Comment by Mazz1224** [comment]
I can also confirm this crash.

https://gist.github.com/Mazz1224/ee8710ef9633a1e91a6bb518731b4f4f#file-crash-2018-07-21_23-33-49-server

**Comment by Demoniaque** [comment]
Fixed. Next update coming out in a bit.
