### ISSUE TITLE
Unable to update codex with new spells since update to 0.9.1 (can not create spells)

### ISSUE THREAD

**Issue by demfels** [TeamWizardry/Wizardry#149]
I get a red colored error on the screen saying "The book didn't load correctly".  It keeps the regents from the previous spell crafted on the codex.  I attempted just crafting a new codex and it seems to have cleared the previous spell from it, but still won't update with any new spells.  When I craft a spell on the research table and click save it says 'saved successfully', but no luck, still won't show up in codex with the reagents needed.

Screen print: https://drive.google.com/file/d/130gfJhDwlRTf1hMQz41xAvPNYJxpkofT/view?usp=sharing

**Comment by Demoniaque** [comment]
Should be fixed in 0.9.2. report back if it didn't work.
