### ISSUE TITLE
Spells not working and unicorns not dropping anything.

### ISSUE THREAD

**Issue by Quinthelas** [TeamWizardry/Wizardry#150]
I made couple of spells, first one I thought was made in correctly, but the other two didn't work either, the third one was the projectile with line to frost effect spell that was written as an example, I have 0.9.2 version on our server as the 0.9.1 was refusing to save the spells. Lastly while I was hunting for unicorns I noticed they were only dropping experience, even after killing over 20 of them I did not get any leather or horns as I had seen in videos so I had to use creative mode for the horn. (I always did the spell while in survival)
Edit: It seems most of the effects are not visible either, such as the mana orbs on top of the holders do not show.

**Comment by Demoniaque** [comment]
> but the other two didn't work either

And how are we supposed to know what the problem is if you don't tell us 
1) what the spell you made is
2) at what step it fails
3) what you tried to do

Did the crafting fail? Did the nacre pearl not save the spell after crafting? Did the book not show you the spell? Is the spell itself correct but not casting? What even is the spell you tried?

Also did 0.9.2 fix the book crashes? I'd like to know that.

We're looking into the unicorn bug.

**Comment by Quinthelas** [comment]
My apologies, I tried beam -> burn and projectile -> frost spells, in both the beam and projectile were first and then linked to the effect, they seemed to fail when I tried casting them from a staff, regardless if I was targeting a mob or air, as for the book crash not sure what you mean, but it did save the spell recipe at least.

**Comment by Demoniaque** [comment]
Very thorough, thank you.

You're on a server, correct? That's the last bit of information i need.

**Comment by Quinthelas** [comment]
Yes I am on a server, with the two other required mods installed, we are also using Astral Sorcery and Thaumcraft in combination with your mod to have more fun options in case you happen to know of any problems with them influencing your mod negatively.

**Comment by Demoniaque** [comment]
Thank you. I'll work on them.

**Comment by Quinthelas** [comment]
You're welcome, I shall look forward to new updates, and I shall keep testing various spells with my friends to see which work, I know if the gravity ones work I will be in huge trouble due to one of my friends immediately using them... XD

**Comment by Demoniaque** [comment]
Fixed most of these.
