### ISSUE TITLE
Game Crashing Bug

### ISSUE THREAD

**Issue by Spartankat** [TeamWizardry/Wizardry#151]
What happened is I created a new spell, Beam->On block collision->Break(there are no modifiers to the Beam or Break). I mounted it on a staff and held it in my hand which froze the game and crashed it to a white background with strange white rectangles before closing the game altogether. I tried to log back into the world after the crash and i received the same white background with the strange symbols. Luckily i had backups of the world and tried it again, created the same spell and crafted it with a staff. I scrolled over the wand in my hotbar and the game crashed with the same screen. This bug does crash the game but not the world, if you were to somehow manage to delete the wand form your inventory then log on to the world it would be fine. Im still playing around with it and have possibly found the problem. the wand will work if im looking at blocks close to me, around 5 blocks however if i look over at blocks far away it crashes to the white screen. Im guessing the game doesn't know what to do if the wand doesn't have a range increase.
-Minecraft version 1.12.2
-Wizardry version 0.9.2
-LibrarianLib version 4.11
- Forgelin version 1.7.4
I have a 110 other mods installed. (no Optifine)
here is a picture of the white background
![desktop 2018 07 24 - 14 34 22 01_moment](https://user-images.githubusercontent.com/41651127/43167934-3f564d62-8f50-11e8-80b6-64032603257b.jpg)

**Comment by Demoniaque** [comment]
Yes I'm sure we can deduce where the bug is by a white crash without a crash report.

Paste ur crash report in pastebin or hastebin and send it here please.

**Comment by Spartankat** [comment]
https://pastebin.com/3ReKeV0u

**Comment by Demoniaque** [comment]
Fixed, thank you.
