### ISSUE TITLE
Issues with Projectile Reinforcements (Can cause crashing)

### ISSUE THREAD

**Issue by penguinken9** [TeamWizardry/Wizardry#154]
Mods Used in initial testing: Wizardry 0.9.3, Forgelin, Librarianlib, Baubles (other mods added later but after confirmation that crashes happened with only these initial mods). Tested against slimes and they did not attack slimes (don't know if this is intentional). When used to combat a skeleton game crashed (repeated this several times kept happening). When used to combat a witch game crashed (same thing happened several times). Against Enderman same thing as with skeletons and witches game crashed. 
Crash Report without the additional mods: https://hastebin.com/ayijuyasez.cs
Crash Report with the additional mods: https://hastebin.com/yomepudesi.sql
If you need any other information or if I did this wrong please let me know.

**Comment by SwissCheese5** [comment]
Does this still exist on the latest wizardry?
