### ISSUE TITLE
Game Crashes on opening book while spell is active

### ISSUE THREAD

**Issue by Norava** [TeamWizardry/Wizardry#155]
Pack used: ATM 3 v5.9.8d
Wizardry Version: 0.9.3 (Due to issues with Twilight Forest and a small playerbase of mostly friends I updated to the latest version after talking to Demoniaque)

Issue:
On attempting to create a spell, while I can see the ingredients
Crashlog with old Spellbook
[crash-2018-07-28_05.45.32-client.txt](https://github.com/TeamWizardry/Wizardry/files/2237944/crash-2018-07-28_05.45.32-client.txt)
Crashlog  with new Spellbook
[crash-2018-07-28_06.43.41-client.txt](https://github.com/TeamWizardry/Wizardry/files/2237945/crash-2018-07-28_06.43.41-client.txt)

 in  the   In-World book, I can't open the book to try to see what those ingredients ARE.
I've tested with a fresh book to make sure it's nothing with my current book

Steps to repeat:
Create a spell and save
Attempt to open book UI via Right Click

**Comment by Demoniaque** [comment]
Use pastebin/hastebin pls.

**Comment by Demoniaque** [comment]
Is the old spellbook from earlier versions?

**Comment by Norava** [comment]
Old Spell Codex (From Version 0.8.5)
https://pastebin.com/n1ZrN7z3
Fresh Spell Codex
https://pastebin.com/G3UnrrGT

**Comment by Demoniaque** [comment]
update liblib
