### ISSUE TITLE
[1.12.2] Missing capability with JEI Resources DIY Ore graphing  

### ISSUE THREAD

**Issue by aking4125** [TeamWizardry/Wizardry#158]
This was already reported on the [JEIR issue tracker](https://github.com/way2muchnoise/JustEnoughResources/issues/152). It's posted here just in case they cannot fix it on their end. Here is the rewriting of the issue: 

Using the /profile command (Via JEIR) in any dimension causes the game to [crash](https://paste.dimdev.org/opotuguliq.mccrash) with the following crash log. I think [this is the Wizardry mod in question](https://minecraft.curseforge.com/projects/wizardry-mod?gameCategorySlug=mc-mods&projectID=278155 ).

Not to be confused with [Electroblob's Wizardry](https://minecraft.curseforge.com/projects/electroblobs-wizardry?gameCategorySlug=mc-mods&projectID=265642). I think

[crash-2018-07-31_22.23.07-server.txt](https://github.com/way2muchnoise/JustEnoughResources/files/2247782/crash-2018-07-31_22.23.07-server.txt)

Sorry if this was already reported.

**Comment by pau101** [comment]
Thanks for the report! However, this does in fact seem to be an error on the side of JustEnoughResources. I have responded to the original issue with the explanation.
