### ISSUE TITLE
Enigmatica 2 modpack

### ISSUE THREAD

**Issue by Gr1mJ0ck3r** [TeamWizardry/Wizardry#161]
Orbs dont render in the orb altar.
Crafting spells dont show the configurations of the shapes and effects.

**Comment by murapix** [comment]
Need mod version, as this may have already been fixed.

**Comment by NillerMedDild** [comment]
He's using `wizardry-0.9.3` :)

**Comment by Gr1mJ0ck3r** [comment]
Clicking in the spells is not showing the modifiers

**Comment by murapix** [comment]
Ah, that makes a lot more sense. *That* issue is something on BetterFPS's end, for which we have already opened an issue.
