### ISSUE TITLE
Crash upon opening codex when it has a spell recipe

### ISSUE THREAD

**Issue by JRoffel** [TeamWizardry/Wizardry#163]
[crash-2018-08-06_20.59.46-client.txt](https://gist.github.com/JRoffel/8ca2f24af342f2ee2bb521e8f88e3bb4)

When opening the codex IF it has an active spell recipe stored, the game freezes for a while, then crashes, this does not happen if the codex does not contain any spell recipe.

Running the normal All the Mods 3 modpack, with only Wizardry updated to it's latest version for the cape bugfix.

**Comment by murapix** [comment]
Look for similar issues before opening a new one.
