### ISSUE TITLE
CRASH Random crash when chunk loads tickEntity

### ISSUE THREAD

**Issue by Akaruz64** [TeamWizardry/Wizardry#164]
It happens randomly when loading the chunk, sometimes right when i load the world, sometimes after a few hours of playing.

https://pastebin.com/ELC1jSWe

Using Forge Version: 2747 and Wizardry 0.9.3

**Comment by murapix** [comment]
Ah, finally, someone else who has this issue. Still trying to get the original reporter (owner of a server I play on) to test my fix for it.

**Comment by Akaruz64** [comment]
Nice to know that im not the only one with this issue, i currently have it in single player, if you want i can test the fix in a copy of my SP world

**Comment by murapix** [comment]
Does the new version uploaded today fix your issue?

**Comment by Akaruz64** [comment]
Hey, i remade my altar, and when i placed my last gem holder i get a instant CTD, and everytime i try to log in to the world with the following message/crash log:

The game crashed whilst rendering block entity
Error: java.lang.NoClassDefFoundError: com/teamwizardry/librarianlib/features/math/interpolate/numeric/InterpFloatInOut

https://pastebin.com/7E9TqNVw

Using your latests version 0.9.5 im gonna try now with 0.9.4

**Comment by Demoniaque** [comment]
Update LibLib
