### ISSUE TITLE
Mortar Glitch, witch items.

### ISSUE THREAD

**Issue by pingvikin** [TeamWizardry/Wizardry#165]
When I try to open the Altar with an empty Hand without having a level, it does not come out. 
But i clicked an any item on the Altar, i can use its interface.
![image](https://user-images.githubusercontent.com/26678843/43929083-1097c43a-9c3c-11e8-814c-ec4187404a8b.png)

Mod version: 0.9.4

**Comment by murapix** [comment]
Wrong mod, this issue is with Vampirisim, go [here](https://github.com/TeamLapen/Vampirism/issues) for their issues page.
