### ISSUE TITLE
Spell Recipe tab causes crash

### ISSUE THREAD

**Issue by penguinken9** [TeamWizardry/Wizardry#166]
So better explanation is upon creating a new world and opening the book immediately clicking the spell recipe tab before linking a spell together to even be in it causes a crash. Basically if you click the tab before a spell has been saved to the book it causes a crash. Link to the hastebin is here: https://hastebin.com/wusixegeto.bash . Problem does go away once you save a spell that then goes in the book. Pretty minor for existing books but if someone randomly clicks it when they first start might cause an issue.

**Comment by JustJinxed** [comment]
Also observed, which starting out is becoming a hazard, as I have no idea how to create a spell yet, and keep accidentally clicking this!

**Comment by Demoniaque** [comment]
Update liblib.

**Comment by Demoniaque** [comment]
(and update wizardry)
