### ISSUE TITLE
It isn't clear what materials the structures are composed of

### ISSUE THREAD

**Issue by Skyshayde** [TeamWizardry/Wizardry#169]
One of the players on my server had some troubles figuring out what the quartz blocks in the structures were.  My first experience with the structure building was in creative with the auto create so I can't really say how difficult it is to recognize it myself, but with the transparency it pretty much does look like any other white block.  It might be worth giving a brief overview of what the structures are made of in the guidebook.  

Thanks!

**Comment by Demoniaque** [comment]
Update liblib and the mod, we added a materials tab
