### ISSUE TITLE
Suggestion/request

### ISSUE THREAD

**Issue by kragnoth** [TeamWizardry/Wizardry#181]
Would it be possible to add a cosmetic alternative to the halo?  Maybe a wizard's hat?

I just find the halo too thematically breaking to use this mod in any serious fashion.  (The syringes system aside)

**Comment by YaibaToKen** [comment]
That reminds me of Witch Hunter (it's a manhwa). Witches' hats are their source of magical power, acting like a battery and generator at the same time. The stronger their hats, the more powerful the witch, and having their hat stolen (or worse, destroyed) is a source of great shame and humiliation.

Are add-ons for Wizardry possible at this point in time? If so, and based on @kragnoth 's suggestion, I'd love making an addon with witch and wizard hats, inspired on the mentioned manhwa.

**Comment by SwissCheese5** [comment]
No sorry.
Wizardry addons are possible however. @YaibaToKen
