### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by drewbit** [TeamWizardry/Wizardry#183]
Wizardry Version: wizardry-0.9.6
LibrarianLib Version: librarianlib-1.12.2-4.12
Forgelin Version: wizardry-0.9.6
Forge Version: 14.23.4.2759

Getting this crash when I boot the server.

https://pastebin.com/ncdL1MhG

**Comment by Demoniaque** [comment]
https://github.com/TeamWizardry/Wizardry/blob/45736a71e2fa9a5e1b54130948998e6add26c316/src/main/java/com/teamwizardry/wizardry/proxy/CommonProxy.java#L82

Gonna need more information on the crash I think....

**Comment by SwissCheese5** [comment]
Update java probably.
