### ISSUE TITLE
Server crash on wisdom wood using atomic disassembler

### ISSUE THREAD

**Issue by Yoosk** [TeamWizardry/Wizardry#186]
Used Atomic Disassembler in vein mode from Mekanism on Wizardry wisdom wood tree, which ended in [crash](https://gist.github.com/15e64afbbd0810eb92a8612867549e0f).

All The Mods 3 - Remix v0.0.3

Mekanism issue for reference: https://github.com/aidancbrady/Mekanism/issues/5146

**Comment by Bluexin** [comment]
I will fix this because it's just adding one character on our side, but in my opinion it should be on Mekanism's side to fix it.
That method is absolutely not meant to be used the way they're using it.

**Comment by NillerMedDild** [comment]
Is this fix present in `librarianlib-1.12.2-4.15`? One of my players just reported it.

**Comment by Bluexin** [comment]
Seems to be in 4.16 snapshots.
We'll look for a suitable version to be published to curse.

**Comment by NillerMedDild** [comment]
Thank you :D

**Comment by Bluexin** [comment]
Though it looks like it got fixed on mekanism side as well : https://github.com/aidancbrady/Mekanism/commit/b0bfdd34334edab42b32f5fd1b5b71766c227429
No idea whether they published it, but that is the correct fix (ours is a workaround we shouldn't have had to do in the first place).
