### ISSUE TITLE
Crash when saving spell to codex. 

### ISSUE THREAD

**Issue by VoilaTada** [TeamWizardry/Wizardry#192]
Made a spell using Projectile (10x range, 10x speed)->On Block Collision -> Zoom(10x range).  Then went to save the spell to my codex and my client crashed. Server did not crash. 

Here is a paste bin of my forge log from the last message sent in game chat till the crash. https://pastebin.com/JGaffeqd 

And attached is the crash report.
[crash-2018-09-16_12.16.09-client.txt](https://github.com/TeamWizardry/Wizardry/files/2386769/crash-2018-09-16_12.16.09-client.txt)

**Comment by SwissCheese5** [comment]
Should no longer exist
