### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Aphenon** [TeamWizardry/Wizardry#198]
I get a crash when trying to start my server. 
https://pastebin.com/dPG1gxWR

**Comment by Demoniaque** [comment]
Did you get your mod jar from any website other than curseforge?

**Comment by Aphenon** [comment]
Its a modified version of All the Mods 3. Added some mods. All mods are from Curseforge.

**Comment by PresidentBacon** [comment]
This is caused by Better Foliage being present on the server.

**Comment by Demoniaque** [comment]
Hmm, I thought we fixed that...
