### ISSUE TITLE
Clients randomly crash with NoClassDefFoundError

### ISSUE THREAD

**Issue by tpbcnote** [TeamWizardry/Wizardry#200]
Just as a first disclaimer, we initially had some issues with a different mod on our server being incompatible with the latest versions of Forge, so we are using 2765. If that is a huge impact we can try to revisit, but I'm hoping not for the following reasons. We initially had some problems loading the server with the latest versions of Wizardry (0.9.7) and LibrarianLib (4.15), where we were getting errors that were similar but not identical to the one reported here: https://github.com/TeamWizardry/Wizardry/issues/198 .

If need be I can go back and try to retrieve the exact messages, but we managed to resolve those by rolling back to version 4.11 of LibrarianLib, which also entailed rolling back to version 0.9.5 of Wizardry (as 9.6 requires 4.12+). The server is now loading up just fine, though eventually one of our connected clients (there are three of us currently using the server) will crash with the following error. There are three client crash reports at this link, separated by 5 lines of dashes: https://pastebin.com/NJXys8An

I'm completely guessing here, but it seems like they are being caused by an issue retrieving a particle effect for the mana fluid block?

**Comment by murapix** [comment]
The first two are using hacked versions of Wizardry that have been illegally posted online - make sure everyone's only sources of mods are Curseforge, Github, and modders' personal websites.

As for the third crash log, I'm not actually sure why that's happening. InterpFloatInOut was made in LibrarianLib 4.10, so it shouldn't be missing. Try having them get fresh copies of the mods, I guess?

**Comment by tpbcnote** [comment]
Called it! I'll chalk this one up as exhaustion induced idiocy.
