### ISSUE TITLE
Minecraft wont initialize

### ISSUE THREAD

**Issue by Stormbender0025** [TeamWizardry/Wizardry#201]
I have been trying to play the wizardry mod on 1.12.2. I have installed all latest files and also the latest forge 1.12.2. No matter what i do, the game will crash while initializing LibrarianLib.

The log is as follows:
### Crash Log
\[20:10:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker[20:10:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker[20:10:16] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker[20:10:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker[20:10:16] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2770 for Minecraft 1.12.2 loading[20:10:16] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_65, running on Windows 7:x86:6.1, installed at C:\Program Files\Java\jre1.8.0_65[20:10:16] [main/INFO] [FML]: Searching C:\Users\admin\AppData\Roaming\.minecraft\mods for mods[20:10:16] [main/INFO] [FML]: Searching C:\Users\admin\AppData\Roaming\.minecraft\mods\1.12.2 for mods[20:10:16] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.2.18.jar. This is not recommended, @Mods should be in a separate jar from the coremod.[20:10:16] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft[20:10:16] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed![20:10:16] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in EluLib-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.[20:10:16] [main/WARN] [FML]: The coremod FMLPlugin (elucent.elulib.asm.FMLPlugin) is not signed![20:10:16] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.7.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.[20:10:16] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft[20:10:16] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed![20:10:16] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in librarianlib-1.12.2-4.15.jar. This is not recommended, @Mods should be in a separate jar from the coremod.[20:10:16] [main/WARN] [FML]: The coremod com.teamwizardry.librarianlib.asm.LibLibCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft[20:10:16] [main/WARN] [FML]: The coremod LibrarianLib Plugin (com.teamwizardry.librarianlib.asm.LibLibCorePlugin) is not signed![20:10:16] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in wizardry-0.9.7.jar. This is not recommended, @Mods should be in a separate jar from the coremod.[20:10:16] [main/WARN] [FML]: The coremod com.teamwizardry.wizardry.asm.WizardryCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft[20:10:16] [main/WARN] [FML]: The coremod Wizardry Plugin (com.teamwizardry.wizardry.asm.WizardryCorePlugin) is not signed![20:10:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker[20:10:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker[20:10:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker[20:10:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker[20:10:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[20:10:20] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557[20:10:20] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc[20:10:20] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[20:10:20] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[20:10:20] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker[20:10:20] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[20:10:20] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[20:10:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[20:10:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[20:10:21] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker[20:10:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker[20:10:21] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}[20:10:21] [main/INFO] [STDOUT]: [com.teamwizardry.wizardry.asm.WizardryTransformer:log:28]: [wizardry ASM] Successfully patched -> 'func_70071_h_', 'onUpdate' with '()V'[20:10:21] [main/INFO] [STDOUT]: [com.teamwizardry.wizardry.asm.WizardryTransformer:log:28]: [wizardry ASM] Successfully patched -> 'func_191986_a', 'travel' with '(FFF)V'[20:10:21] [main/INFO] [LibrarianLib ASM]: Transforming Entity[20:10:21] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [onUpdate, func_70071_h_] Descriptor ()V)[20:10:21] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Update hook[20:10:21] [main/INFO] [LibrarianLib ASM]: Patch result: Success[20:10:21] [main/INFO] [STDOUT]: [com.teamwizardry.wizardry.asm.WizardryTransformer:log:28]: [wizardry ASM] Successfully patched -> 'func_70091_d', 'move' with '(Lnet/minecraft/entity/MoverType;DDD)V'[20:10:26] [main/INFO] [net.minecraft.client.Minecraft]: Setting user: Storm[20:10:27] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:229]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState][20:10:27] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:241]: Transforming net.minecraft.block.Block Finished.[20:10:34] [main/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4[20:10:35] [main/INFO] [FML]: -- System Details --Details: Minecraft Version: 1.12.2 Operating System: Windows 7 (x86) version 6.1 Java Version: 1.8.0_65, Oracle Corporation Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation Memory: 96814624 bytes (92 MB) / 238960640 bytes (227 MB) up to 523501568 bytes (499 MB) JVM Flags: 6 total; -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: Loaded coremods (and transformers): Wizardry Plugin (wizardry-0.9.7.jar) com.teamwizardry.wizardry.asm.WizardryTransformerFMLPlugin (EluLib-1.12.2.jar) elucent.elulib.asm.ASMTransformerForgelinPlugin (Forgelin-1.7.4.jar) CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar) team.chisel.ctm.client.asm.CTMTransformerLibrarianLib Plugin (librarianlib-1.12.2-4.15.jar) com.teamwizardry.librarianlib.asm.LibLibTransformer GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2555' Renderer: 'Mobile Intel(R) 4 Series Express Chipset Family'[20:10:35] [main/INFO] [FML]: MinecraftForge v14.23.5.2770 Initialized[20:10:35] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.[20:10:35] [main/INFO] [FML]: Replaced 1036 ore ingredients[20:10:36] [main/INFO] [FML]: Searching C:\Users\admin\AppData\Roaming\.minecraft\mods for mods[20:10:36] [main/INFO] [FML]: Searching C:\Users\admin\AppData\Roaming\.minecraft\mods\1.12.2 for mods[20:10:38] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 164196043 nanos[20:10:38] [main/INFO] [FML]: Forge Mod Loader has identified 17 mods to load[20:10:40] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, elucore, autoreglib, baubles, crissaegrim, ctm, elulib, embers, forgelin, jei, librarianliblate, librarianlib, psi, wizardry] at CLIENT[20:10:40] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, elucore, autoreglib, baubles, crissaegrim, ctm, elulib, embers, forgelin, jei, librarianliblate, librarianlib, psi, wizardry] at SERVER[20:10:41] [main/INFO] [LibrarianLib ASM]: Transforming Particle[20:10:41] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [getBrightnessForRender, func_189214_a] Descriptor (F)I)[20:10:41] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Potion particle glow[20:10:41] [main/INFO] [LibrarianLib ASM]: Patch result: Success[20:10:41] [main/INFO] [STDOUT]: [com.teamwizardry.wizardry.asm.WizardryTransformer:log:28]: [wizardry ASM] Successfully patched -> 'func_76979_b', 'doRenderShadowAndFire' with '(Lnet/minecraft/entity/Entity;DDDFF)V'/

**Comment by murapix** [comment]
1. Put your logs in Pastebin, Hastebin, or Gist links.
2. This log has nothing about any crash.
