### ISSUE TITLE
Crafting Plate picks up seemingly unlimited amounts of mob drops in world

### ISSUE THREAD

**Issue by GeekBeam** [TeamWizardry/Wizardry#208]
whenever a Spell crafting multiblock is made with the crafting plate in the center, on occasion I would go out and venture pretty far, and getting back, I would see items that had somehow fallen onto the Crafting plate and were now floating around the structure.

I didn't particularly mind at first (I actually found it silly enough to keep it), not until the amount of items that the plate was holding started to go up an unreasonable amount. **the primary issue** mostly lies in regard to the LARGE amount of particles that the plate can generate when it has a large amount of disparate items, because that **started to cause some FPS drops**

maybe there should be a cap to the amount of items the Crafting plate can hold at a time, to help prevent LARGE amounts of items hovering around the structure and causing that lag, especially since the plate can _pick up items in the world, even mob drops, and gather quite a cloud overtime._

that, or make it so that inputting items into the plate needs to be done via right click, instead of simply dropping them (that way the plate can't pick up anything it's not meant to)

[a gif of the item cloud that had accumulated after an hour of playtime.](https://puu.sh/BX7Z2/6f917cd5b2.gif)

**Comment by Demoniaque** [comment]
The limit of the plate is that of a double chest iirc. I'm more curious as to how you're having mobs die specifically on the plate and specifically when you aren't near it.

**Comment by GeekBeam** [comment]
I am not sure myself. the only thing that I CAN say is that the drops collected are being collected at a significant range, as I had no slime islands ANYWHERE near the plate, yet there are clearly blue slime balls amongst the other riff raff.

**Comment by GeekBeam** [comment]
an update: the plate has picked up items dropped from mobs in the Nether, the chunk the plate exists in is not loaded so...I am unsure what is occuring here.

**Comment by PhotonChaos** [comment]
I can't seem to reproduce this issue, and the plate stops picking up items via drop after a certain point. If this issue persists with the newest version of Wizardry and LibLib, please leave a comment on this issue.
