### ISSUE TITLE
Wizardry & Flux Networks conflict

### ISSUE THREAD

**Issue by TacticalUniverse** [TeamWizardry/Wizardry#212]
Both Wizardry Devil dust and Flux from Flux Networks are created by throwing Redstone into the fire. Currently, there is no way to make wizardry devil dust.

**Comment by Demoniaque** [comment]
We solved this by adding a recipe for redstone blocks. Throw redstone blocks into fire. This is the only way we could solve this, sorry.

**Comment by TacticalUniverse** [comment]
ok @Demoniaque how would I add a recipe for that cause I am not sure

**Comment by Demoniaque** [comment]
It should already be in

**Comment by murapix** [comment]
![image](https://user-images.githubusercontent.com/12856095/48317524-6ebdd080-e5a8-11e8-9988-8b31df804882.png)
![image](https://user-images.githubusercontent.com/12856095/48317526-7a10fc00-e5a8-11e8-8b7f-b0103804e7c6.png)

Working fine on our end, you're either not waiting long enough or the pack you're playing with has the recipe removed.
