### ISSUE TITLE
SpellProjectile serialization wrong

### ISSUE THREAD

**Issue by Avatair** [TeamWizardry/Wizardry#219]
SpellRing is serialized two times:
https://github.com/TeamWizardry/Wizardry/blob/master/src/main/java/com/teamwizardry/wizardry/common/entity/projectile/EntitySpellProjectile.java#L332

**Comment by Demoniaque** [comment]
ok
1) why not fix that directly
2) how has spelldata been serializing this whole time?
3) wat

**Comment by Avatair** [comment]
My order of thinking was reversed :)
1. wat
2. how has spelldata been serializing this whole time?
3. better ask before fixing

**Comment by Bluexin** [comment]
https://github.com/TeamWizardry/Wizardry/blame/4c08772b8f989716feec0751fcc5ecf47872ef98/src/main/java/com/teamwizardry/wizardry/common/entity/projectile/EntitySpellProjectile.java#L332
https://github.com/TeamWizardry/Wizardry/commit/cd641e6cfe0ce488b756c4f9c2371ffc74a11ca0#diff-bab6de8b0f107b2c6287afda325a64e5L228
June 19.

**Comment by Demoniaque** [comment]
Fixed.
