### ISSUE TITLE
Place component can consume the wrong item while still placing targeted block.

### ISSUE THREAD

**Issue by Sourpowerpete** [TeamWizardry/Wizardry#22]
https://gfycat.com/OpulentQualifiedIndusriverdolphin

**Comment by Eladkay** [comment]
Each one of those sent each one of us an email notification ;-; try to merge related issues into one issue with a list next time

**Comment by Sourpowerpete** [comment]
Understood, I wasn't told any better till now. I'll place any future Place component issues into one issue.
