### ISSUE TITLE
Modpack GUI Issues

### ISSUE THREAD

**Issue by brandons73** [TeamWizardry/Wizardry#223]
I have tried adding Wizardry to a modpack me and a friend are working on building, but there are some GUI issues we are having. The GUI's aren't showing properly. I would like to know if I have a mod incompatibility, or if it's just a development issue that would be fixed in a future update.  I have tried the mod load order, with no luck.  Any help would be very much appreciated. 

[ModList.txt](https://github.com/TeamWizardry/Wizardry/files/2674749/ModList.txt)

Screenshots:

![2018-12-12_23 06 55](https://user-images.githubusercontent.com/45839960/49919997-368f0380-fe6e-11e8-8bc7-8ff22deaa42f.png)
![2018-12-12_23 17 10](https://user-images.githubusercontent.com/45839960/49920002-3858c700-fe6e-11e8-93a2-5e56094736cc.png)

**Comment by murapix** [comment]
Does anything show up in the game log when you open one of our GUIs? Could you give us a pastebin of the log right after you've opened a GUI?

**Comment by gggg336** [comment]
Is your Forge version 2781+? The newer versions of Forge breaks a lot of mods' rendering techniques. I recall when I was using 2776, the GUIs of Wizardry was still working, so it is probably the new Forge rendering stuff.

**Comment by SamHubert** [comment]
I'm trying to make a modpack of my own at the moment and I removed Angel of Vengeance, Which seemed to partially fix the issue
![2019-01-19_17 19 12](https://user-images.githubusercontent.com/38895808/51433740-61f3d380-1c0e-11e9-920d-d91e09dd47e1.png)

**Comment by ORIN5894** [comment]
https://minecraft.curseforge.com/projects/pagemaster-2
modpack you requested

**Comment by originix** [comment]
https://minecraft.curseforge.com/projects/dogma Conflict between AoV and Wizardry causing Wizardry codex to not load properly. When removing AoV codex works as intended.

**Comment by murapix** [comment]
Tama's fixed this on his end, and the LibLib folks know to check for similar issues on our end
