### ISSUE TITLE
Book didn't load correctly, spell is not binding to pearl

### ISSUE THREAD

**Issue by Testerro** [TeamWizardry/Wizardry#224]
When I open book, the red error "The book didn't load correctly" popups.
When I get spell recipe and drop everything on crafting plate in given order, the ingredients is flying around, but nothing else happen.

Screenshots there: https://imgur.com/a/r5YqyD1

Also this happened me _once_: https://github.com/TeamWizardry/Wizardry/issues/192

Latest version of wizardry and librarian, server forge 1.12.2 - 2772
Mods I have:
BetterFPS,
HelpFixer,
mocreatures,
thutessentials & thutpermissions,
tickdynamic,
bloodmoon,
Rex's additional structures,
Deadly monsters,
CustomNPC,
Waystones,
Twilight Forest,
Reforged Mod,
Moarores

**Comment by Demoniaque** [comment]
Works fine here. did you throw a nacre pearl in the end? are all your mana orbs full of mana?

**Comment by SwissCheese5** [comment]
Shouldve been fixed by now.
