### ISSUE TITLE
Staff items can still cast spells when pearl is removed

### ISSUE THREAD

**Issue by Deffers** [TeamWizardry/Wizardry#225]
When crafting a staff with a valid spell pearl, the pearl adheres to the staff as intended. When placing that staff in the crafting grid again, it separates into a pearl and staff again-- however, the staff remains capable of casting whatever spell was attached to it in the first place. The now-pearl-less staff still requires mana to cast and functions just as it did before-- just without the pearl. It can also accept a new pearl, which will overwrite the spell effect "stored" in the staff.

**Comment by Demoniaque** [comment]
Fixed
