### ISSUE TITLE
Break Spell effects does not drop certain items from other mods

### ISSUE THREAD

**Issue by Deffers** [TeamWizardry/Wizardry#227]
Testing a break spell effect across various mods, I discovered that certain mod items that can be broken by hand or with a pick to produce their drops will not in fact drop at all when broken using the break spell effect. It is worth noting that these items do drop when broken with other remote block breaking items from other mods, such as Thaumcraft's casting gauntlet, so this leads me to believe it is an issue with Wizardry itself. Affected blocks so far:

-Astral Sorcery's Lens, Prism Lens, and Collector Crystals

-Integrated Dynamics' Inventory Reader

-Ender IO's Ender Fluid Conduit

**Comment by Demoniaque** [comment]
Fixed.
