### ISSUE TITLE
Disarm spell effect causes dropped tool to be instantly picked up

### ISSUE THREAD

**Issue by Deffers** [TeamWizardry/Wizardry#228]
When using an Arc->Disarm spell effect, the tool in the target's hand will not drop to the ground, but be instantly picked up by the target. This takes the item out of their hotbar usually but keeps it in their inventory.

**Comment by murapix** [comment]
This was in fact not the item being dropped and instantly picked up, but the spell attempting to move the item to a different hotbar slot before dropping it on the ground. As this is not in line with the intent of the spell, I have removed the offending code.
