### ISSUE TITLE
Realistic Item Drops and Making Pearls

### ISSUE THREAD

**Issue by MokahTGS** [TeamWizardry/Wizardry#229]
Looks like the crafting mechanic for making Nacre Pearls isn't compatible with the Realistic Item Drops mod which makes items dropped in liquid float.  The floating seems to negate the time the pearl is in the liquid and all you ever get is wasted pearls.

Is there any way that this can be changed without removing the realistic item drop mod?

**Comment by Bluexin** [comment]
Realistically, a lot of things don't float in water...
Do they not have a blacklist?

**Comment by MokahTGS** [comment]
Doesn't look like it.

**Comment by Demoniaque** [comment]
Send this issue to realistic item drops.

They need a black list, tons of mods need items in water. AE2 to name one off the top of my head.
