### ISSUE TITLE
Spells don't work

### ISSUE THREAD

**Issue by CherciuRares** [TeamWizardry/Wizardry#237]
Whenever i create a spell everything works fine , but when i try to use it , it just doesn't do anything . I tried it in singleplayer and it works , it seems like it's a problem with my server can anyone help please ?

**Comment by Demoniaque** [comment]
We need much more information.

**Comment by CherciuRares** [comment]
When i use a spell on my server it just makes the animation , i have tried a few and the projectile works , but the beam for example doesn’t do anything except for the animation

**Comment by Demoniaque** [comment]
We still need more information. Show us the whole spell, do you have mana? Do you have a halo? Are you wearing a cape? What did you do exactly?
