### ISSUE TITLE
Crash on spellcast (beam+break)

### ISSUE THREAD

**Issue by homemmakako** [TeamWizardry/Wizardry#239]
When casting a beam to break blocks the game crashes

MC: 1.12.2
Forge: 14.23.5.2808
Wizardry: 0.9.9

[Crashlog](https://pastebin.com/uwhfEHKZ)

**Comment by meteovio** [comment]
Having the same issue with a Projectile + On Block Collision + Break

[Crashlog](https://pastebin.com/NTzNKLz0)

**Comment by murapix** [comment]
Was fixed back on Jan 13 (after 0.9.9), somehow missed this issue being made. Will be in our next update
