### ISSUE TITLE
Server crash when using some spell

### ISSUE THREAD

**Issue by Shacauto** [TeamWizardry/Wizardry#242]
Server crash many times when using some spell so i stopped using them for the moment.
This time i used projectiles->entity collision -> decay -> shatter.
[crash-2019-02-07_12.40.04-server.txt](https://github.com/TeamWizardry/Wizardry/files/2840621/crash-2019-02-07_12.40.04-server.txt)
I attach the server crash report to the post.

**Comment by AkitoKamimura** [comment]
I had the same problem, some spells crashed.
I tryed to find out what spell does the crash and it seems to be the one that changes the targets to "entitys". I tryed many variations of the same spell with different targets, set it to blocks or dont set it at all would change it.
I hope the modmaker can work on that a bit easyer now :D

**Comment by SwissCheese5** [comment]
Fix in the next update.
