### ISSUE TITLE
Unicorns Not Spawning?

### ISSUE THREAD

**Issue by Estus1999** [TeamWizardry/Wizardry#244]
I've been playing on an Enigmatica 2 (v1.5.8) Server. I went to the Underworld and fairies and Spirit Wights spawn, but not a single unicorn is there. I am the only person to have gone to that dimension yet, and I have sat around in one place for an hour or so waiting for one to spawn, and I've tried traveling to see if they would spawn as I travel, but no luck. Thank you very much in advance for any help.

**Comment by mindbane** [comment]
I came here to ask this very question. I also have not found any unicorns

**Comment by Martians6** [comment]
https://youtu.be/fgmXfRad5EI
I spent an hour and nothing spawned :/

**Comment by SiennaWesty** [comment]
I am also having this issue! What is going on :( Can we spawn them in some how? ... Also the dimension is REALLY laggy for being just clouds, I don't get any lag anywhere else!

**Comment by TideSinger** [comment]
We’re working on a fix right now, @SiennaWesty your issue might be related to 1.12 world gen, and should be fixed in the next release

**Comment by SiennaWesty** [comment]
> We’re working on a fix right now, @SiennaWesty your issue might be related to 1.12 world gen, and should be fixed in the next release

Thanks heaps!

**Comment by yrsegal** [comment]
Why am I assigned lmao
