### ISSUE TITLE
Zone > Effect only affects an entity that is clicked on to initiate the spell

### ISSUE THREAD

**Issue by raymoo** [TeamWizardry/Wizardry#246]
It seems like if I make a spell with structure Zone > Effect, it won't affect any entities unless I clicked on the entity to cast the spell.

How to reproduce:
- Create a spell with Zone > Entity > Burn (It is still buggy without the restriction, I just used it to avoid being confused by block fire), with 19 potency, 10 area, and 1 range on zone
- Find an area with multiple mobs
- Click the ground - no mobs will be burn
- Click a mob - that mob will be targeted by burn several times, while the surrounding mobs are not

The expected result for both casting scenarios is that multiple mobs within the area of effect are immolated.

**Comment by SwissCheese5** [comment]
I don't understand. Does the spell not create a zone until you right click an entity? or does it run anywhere but only your clicked entity burns?

**Comment by raymoo** [comment]
Only the clicked one burns.

**Comment by PhotonChaos** [comment]
Going to work on this

**Comment by PhotonChaos** [comment]
After a _lot_ of debugging, zone now works properly. The issue has been fixed!
