### ISSUE TITLE
Range modifier on arc doesn't do anything

### ISSUE THREAD

**Issue by raymoo** [TeamWizardry/Wizardry#247]
It looks like the spread and distance of arc doesn't change based on the range modifier, but that the spread does increase with potency

How to reproduce:
- Make a spell with Arc > Time stop, with no modifiers
- Make the same with 11 range
- Make the same with 27 power and no range
- Make the same with both power and range modifiers
- Cast with all four spells. I observed that the first two look the same, short with a narrow spread, and the last two look the same, short with a wide spread.

I would expect (based on tooltip) that power would increase the density of the cone without increasing the spread, and that the range should increase the spread and distance traveled.

**Comment by raymoo** [comment]
I'm getting inconsistent results. Now it's not increasing the spread even with potency. It also seems like beam distance increases with potency instead of range?

**Comment by raymoo** [comment]
I think something strange is going on with the modifiers here

![2019-02-28_12 57 39](https://user-images.githubusercontent.com/5734399/53591072-cdf42080-3b58-11e9-9cdc-46c9c10c9bfd.png)

**Comment by SwissCheese5** [comment]
Are you sure there's no difference? Range will increase the reach of each arc thrown. You might not notice it because the lines are in front of you.

**Comment by raymoo** [comment]
I tested it by seeing how far away I can hit a mob. You can also see in my other posts that it might be something different than the range modifier simply not working.

**Comment by SwissCheese5** [comment]
Duplicate #275
