### ISSUE TITLE
Crash when mob dies under time slow effect

### ISSUE THREAD

**Issue by raymoo** [TeamWizardry/Wizardry#248]
I'm getting a crash when I kill a mob that is under the effects of time slow. Here are my crash logs: https://paste.ee/p/z7jsn

This crash persists when I reenter the world, but seems to go away if I do it enough times. Just so you know, I am running a mod (Animania) that modifies (replaces?) the vanilla passive mobs. I haven't tried reproducing the crash without the mod.

**Comment by TideSinger** [comment]
Animania is known for being Fun™, can you test it without Animania and get back to us?

**Comment by Bluexin** [comment]
Stack trace looks identical to #242 , if that can help tracking the bug down

**Comment by murapix** [comment]
The paste is gone, but if it was the same as #242, then it looks to be fixed for the next version
