### ISSUE TITLE
Invalid smelting recipe registration

### ISSUE THREAD

**Issue by xxlio109** [TeamWizardry/Wizardry#249]
wizardry-0.9.9
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-672794fe
    Sponge: 1.12.2-7.1.6-SNAPSHOT
    SpongeForge: 1.12.2-2768-7.1.6-RC3613
    Minecraft Forge: 14.23.5.2815

    

> https://gist.github.com/xxlio109/a2bad1a4b3996d6fcb9ae6c55f2e4bc2

**Comment by TideSinger** [comment]
This is a LibLib issue, LibLib is registering the recipie before finishing initialization. It should be fixed in the next build of LibLib
