### ISSUE TITLE
Kick from server with Beam > Sonic Scream

### ISSUE THREAD

**Issue by Kenny-Kipling** [TeamWizardry/Wizardry#250]
If I cast Beam > Sonic Scream on an entity I get kicked from the server with the message "Internal Server Error." This is the log   https://pastebin.com/VbVWJjwe

**Comment by Bluexin** [comment]
That is far from a full log, and afaik wouldn't be enough to get the info -- at least provide the full stack trace of the error.

**Comment by murapix** [comment]
No, that is enough to find the error in this case, and I know it's just one line of code that needs to be deleted.

**Comment by TideSinger** [comment]
Can you provide a full log? I don’t believe any of the dev team have been able to reproduce this issue, so we need the log.

**Comment by Kenny-Kipling** [comment]
Don't believe I have that log anymore. Also this is with version 0.9.9. Forgot to mention that part, sorry.

**Comment by Bluexin** [comment]
https://github.com/TeamWizardry/Wizardry/blob/f9f331527e49b59d3d209300b3ad8e865b02fab1/src/main/java/com/teamwizardry/wizardry/common/module/effects/ModuleEffectSonic.java#L58
Looks like some (bad) debug message was left.
