### ISSUE TITLE
server cashes on start

### ISSUE THREAD

**Issue by tmvkrpxl0** [TeamWizardry/Wizardry#251]
this is server start log: https://del.dog/ibisatakuy.php
and it doesn't create any crash report
version:
wizardry 0.9.9
Librarianlib 4.15
Forgelin 1.8.2
edit:forge version is 2807, and i can't change it unless someone tell me how
and i use java 64bit version build 1.8.0_51-b16, which is i get it from minecraft bundle jre

**Comment by Bluexin** [comment]
Might be an issue with your catserver install, or just an incompatibility with it.
Not sure we want to support that shit tbh.
