### ISSUE TITLE
Loosing spell for an apex pearl

### ISSUE THREAD

**Issue by Endernia** [TeamWizardry/Wizardry#253]
When you have a crafted spell in a pearl if you combine it with a staff and then put the staff in the the inventory 2x2 crafting table, move it to a different slot in the crafting table it will wipe the spell from the staff and give an Apex Pearl in return instead of the pearl with the spell created on it.

https://cdn.discordapp.com/attachments/378812468421459971/563394822082134038/unknown.png

**Comment by yrsegal** [comment]
https://github.com/TeamWizardry/Wizardry/blob/master/src/main/java/com/teamwizardry/wizardry/crafting/irecipies/RecipeUnmountPearl.java#L57

@SwissCheese5
