### ISSUE TITLE
Spirit Wight

### ISSUE THREAD

**Issue by Mugiwaxar** [TeamWizardry/Wizardry#254]
Hello,
I love the Underworld, then, I decided to live here!
But they are a nightmare... How to deal with Spirit Wights ?
I can't kill them, I can't block them, they folow me forever.
Is there a way to make a safe zone ?

**Comment by murapix** [comment]
You can kill them with any form of magic damage (most spells and the unicorn dagger work for this)

**Comment by Mugiwaxar** [comment]
Is there a way to create a safe zone ?
A zone where they don’t spawn ?

**Comment by murapix** [comment]
EnderIO Aversion Obelisk should do the trick, as long as you can get it up to a 128 block range (the spawning range of Wights)
