### ISSUE TITLE
Error serializing PacketSyncModules

### ISSUE THREAD

**Issue by RSAmaro** [TeamWizardry/Wizardry#256]
I noticed this happening when I combined the pearl with the staff, I'm not quite sure tho but that's my best guess.

Spells do not consume mana neither does the action it's suppose to, E.G: Burn projectile on entity (this only happens in multiplayer).

Modpack Base: All The Mods 3
Actual Modpack: All The Cats 3 (on Technic Launcher)

https://hastebin.com/ekovumumub.rb

**Comment by SwissCheese5** [comment]
Can you reproduce the issue every time consistently? Which version of liblib are you using?

**Comment by RSAmaro** [comment]
The part of trying to use spells still doesn't work.
wizardry-0.9.9
librarianlib-1.12.2-4.15

**Comment by SwissCheese5** [comment]
did you run a wizardry command?

**Comment by SwissCheese5** [comment]
packet removed. Shouldn't be a problem later on.
