### ISSUE TITLE
Crash out of no where

### ISSUE THREAD

**Issue by UnSilencedSins** [TeamWizardry/Wizardry#262]
I got this crash out of nowhere so I thought you should know. I'm on 0.10.0

The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Couldn't find a property `slotRadii[0]` in class `com.teamwizardry.wizardry.client.core.renderer.PearlRadialUIRenderer` or any of its superclasses

Edit: I just loaded up the world and it crashed again. same reason

**Comment by murapix** [comment]
Duplicate of #255

**Comment by UnSilencedSins** [comment]
my bad
