### ISSUE TITLE
Crash - couldn't find property

### ISSUE THREAD

**Issue by Vyraal1** [TeamWizardry/Wizardry#263]
LLibrary 1.7.19
Wizardry 0.10.0
Forge 2836

https://gist.github.com/Vyraal1/c24cc661109278a2ab4b5c9daf5eefe8

**Comment by murapix** [comment]
First of all, it's LibrarianLib, not LLibrary.
Second of all, Duplicate of #255 - We know the fix, just figuring out exactly what needs to be merged into the main LibLib branch before we push, and that'll fix the issue.
