### ISSUE TITLE
IC2 compatibility issue (Solution  contains uncountable numbers)

### ISSUE THREAD

**Issue by tyra314** [TeamWizardry/Wizardry#264]
Seems #39 surfaced again.

wizardry: 0.10.0
IC2: 2.8.109-ex112
forge: 14.23.5.2836

Crashlog: https://gist.github.com/tyra314/7d62f80342291d054afb998947004631

When rolling back to wizardy 0.9.9, the crash doesn't happen.

**Comment by murapix** [comment]
Can you throw this on https://bt.industrial-craft.net/ too?

**Comment by tyra314** [comment]
Judging from the old ticket, this should be the culprit: 

https://github.com/TeamWizardry/Wizardry/blob/master/src/main/java/com/teamwizardry/wizardry/common/world/trickery/WorldProviderTorikki.java#L85

**Comment by SwissCheese5** [comment]
WHAT THE FUCK.

**Comment by SwissCheese5** [comment]
FIXED. THANK YOU.
