### ISSUE TITLE
Multiplayer spells not working.

### ISSUE THREAD

**Issue by BoTL1kE** [TeamWizardry/Wizardry#265]
Everything seems to be working fine up until you try to use the created spell with the staff. I am playing in Multiplayer and even had experimented with OP on, Creative mode, everything. They work fine in Singleplayer. The spells I tried were: Beam > Sonic Scream, Beam > On Entity Collision > Frost, Beam > Lightning.
Playing with forge 2795, quark and railcraft.

I can provide more information if needed.

**Comment by SwissCheese5** [comment]
I just experienced this myself by coincidence . Looking into it.

**Comment by BoTL1kE** [comment]
Any news on this issue as to what could be causing it?

**Comment by SwissCheese5** [comment]
I think I managed to fix it but there are a few other multiplayer issues to deal with as well so as soon as I fix those, I'll push out an update
