### ISSUE TITLE
[CRASH] 0.9.9 - Likely Relating to the Clear All Function on Magicians Table

### ISSUE THREAD

**Issue by HalestormXV** [TeamWizardry/Wizardry#268]
https://hastebin.com/amirayivec.rb

Likely a crash related to the implementation of the new "Clear All" function on the Magician's Table. Replicated by placing Beam -->> Lightning -->> On Entity Collision. Yes this shows up as an invalid spell but when you try and click the "Clear" button or if you press almost any key while in that window the entire game crashes to desktop.

Get a second crash also when trying to save a valid spell: (Beam, Entity Collision, Freeze)
https://hastebin.com/ujivinotas.rb

**Comment by SwissCheese5** [comment]
Try this liblib jar please: https://cdn.discordapp.com/attachments/242885249351155713/575850273600307200/librarianlib-1.12.2-4.18-fat.jar

**Comment by HalestormXV** [comment]
Excellent, looks like your revisions fixed the issues. I tried to replicate both crashes again unsuccessfully. Might this link be the one that was just approved on curse?

**Comment by murapix** [comment]
Yes, it is
