### ISSUE TITLE
Can't Use on Aternos

### ISSUE THREAD

**Issue by GreenPlays** [TeamWizardry/Wizardry#270]
I've been trying for about a week to make a modded Aternos server for me and my friends to play on. Every time I add in the Wizardry mod it crashes my client in both multiplayer and single player. I'm using the version 0.10.0.

**Comment by murapix** [comment]
And your LibLib version?

**Comment by GreenPlays** [comment]
4.17

**Comment by SwissCheese5** [comment]
Try 4.18

**Comment by GreenPlays** [comment]
I did, it my forge client said I required 4.17 :P

**Comment by SwissCheese5** [comment]
Update liblib on the server as well..
