### ISSUE TITLE
Can't cast any spells issue

### ISSUE THREAD

**Issue by Gelox1209** [TeamWizardry/Wizardry#272]
It seems like anyway to cast a spell is impossible, here's one of the many errors it spits out when I try to cast a spell with the beam shape. It seems any other kind of shape casting doesn't work either also.

`19.05 00:02:30 [Server] Server thread/FATAL [minecraft/MinecraftServer]: Error executing task
19.05 00:02:30 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/teamwizardry/wizardry/init/ModKeybinds
19.05 00:02:30 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
19.05 00:02:30 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
19.05 00:02:30 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
19.05 00:02:30 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
19.05 00:02:30 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
19.05 00:02:30 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
19.05 00:02:30 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
19.05 00:02:30 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
19.05 00:02:30 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/teamwizardry/wizardry/init/ModKeybinds
19.05 00:02:30 [Server] INFO at com.teamwizardry.wizardry.common.item.ItemStaff.func_77659_a(ItemStaff.java:118) ~[ItemStaff.class:?]
19.05 00:02:30 [Server] INFO at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
19.05 00:02:30 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
19.05 00:02:30 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
19.05 00:02:30 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
19.05 00:02:30 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
19.05 00:02:30 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
19.05 00:02:30 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
19.05 00:02:30 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
19.05 00:02:30 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
19.05 00:02:30 [Server] INFO ... 5 more`

**Comment by Gelox1209** [comment]
Also whenever I open the book it tells me the book didn't load correctly

**Comment by SwissCheese5** [comment]
Will be fixed in the next update.
