### ISSUE TITLE
wizardry-0.10.2 - Crash Related to Illuminate and its Particles

### ISSUE THREAD

**Issue by HalestormXV** [TeamWizardry/Wizardry#276]
wizardry-0.10.2
librarianlib-1.12.2-4.19.1-release.jar

Crash relates to the rendering of the Light Particles created with the Illuminate spell. Last I reported this was on Wizadry 10.0 and I believe it was chalked up to trying to render particles and not doing an isRemote check. Change-log notes that in 0.10.2 the Light spell crash was fixed however it appears it still exists. Now I am not sure how you guys intertwine or update the LibrarianLib and the Wizadry mod but the crash is still present on 0.10.2 (perhaps it is strictly a LibranLib issue?)

However, it still exists and here is the report:
https://pastebin.com/6DVrFM34

Thanks for the work that you guys put into this mod. Appreciate it.

**Comment by SwissCheese5** [comment]
A hot fix will be underway, thank you.
