### ISSUE TITLE
Travelling to Underworld causes invalid move player packet received

### ISSUE THREAD

**Issue by threeringserkus** [TeamWizardry/Wizardry#277]
No crash report, my players accidentally traveled to dim33 and were unable to reconnect. Any attempt was met with error "invalid move player packet received"

Fix was editing their [uuid].dat dimension to 0 (overworld) and using /tp to teleport them to me. They would still disconnect but further logins worked.

One was potentially mounted to a tamed, Ice and Fire, Amphithere

**Comment by SwissCheese5** [comment]
Can we get the error?

**Comment by threeringserkus** [comment]
[https://i.imgur.com/pw6kBe5.png](url)

Is this what you mean by error?

**Comment by SwissCheese5** [comment]
No, paste your whole log right after the error occurred, paste it in pastebin.com and post the link here

**Comment by threeringserkus** [comment]
What log? Like I said originally there is no crash.

**Comment by threeringserkus** [comment]
Finally got a hold of the player. I have the log but it's too large for pastebin. Any suggestions on how to get it to you?

**Comment by SwissCheese5** [comment]
paste the last hundred lines in pastebin

**Comment by threeringserkus** [comment]
https://pastebin.com/AetKzmeP

**Comment by SwissCheese5** [comment]
ok can you paste your whole like in hastebin or gist?

**Comment by threeringserkus** [comment]
https://gist.github.com/threeringserkus/60e77ca7c33660b95fa669edf0ac319f

**Comment by threeringserkus** [comment]
its hella long

**Comment by SwissCheese5** [comment]
Where did you get your wizardry jar file from?

**Comment by threeringserkus** [comment]
Curseforge

**Comment by SwissCheese5** [comment]
You're using sponge, am I reading that right?

**Comment by threeringserkus** [comment]
Not to my knowledge

**Comment by SwissCheese5** [comment]
Most likely outdated jar. Please confirm by updating

**Comment by PhotonChaos** [comment]
I'm unable to reproduce this issue. If this persists with the newest version of Wizardry and LibLib, please comment on this issue.
