### ISSUE TITLE
Having some issues with wizardry mod (crash).

### ISSUE THREAD

**Issue by xelio09** [TeamWizardry/Wizardry#278]
Hello, Im currently playing with some friends on an ftb server and we added some extra mods (like wizardry).

We really want to play this mod on our server but we dont understand everything with crash logs.

https://pastebin.com/0vNybWXC

Thank you for your time.

**Comment by xelio09** [comment]
https://pastebin.com/h2mG1sQb

You might have more information with this one

**Comment by murapix** [comment]
Stop what you're doing, delete the pack, and download them all from https://minecraft.curseforge.com/

You probably want to run a couple virus scans, you've gotten your mods from sites known to be dangerous.

**Comment by SwissCheese5** [comment]
The error is not pointing to anything specific, what was the last thing you did that triggered the crash?

**Comment by xelio09** [comment]
When we open the book and close it with E, or when i want to add extra perks to my spells with the + on the right, i just crash when i click it after draging it to the magician's worktable. i didnt tried to cast spells yet

**Comment by SwissCheese5** [comment]
Do exactly what murapix said.

**Comment by xelio09** [comment]
It works, thx you very much.

**Comment by murapix** [comment]
Get your mods from curseforge, github, or modders' personal sites. Anything else can and will have broken and virus-filled versions of the mods, and cannot be supported by any modders.
