### ISSUE TITLE
pearlswap rendering crash[clientside}

### ISSUE THREAD

**Issue by deviraux** [TeamWizardry/Wizardry#281]
I am getting a client side crash whenever I try and use the pearl belt to swap out the pearl on my staff. 
https://pastebin.com/T0BMbYrz
I am running the latest versions of the mod and its dependencies

**Comment by SwissCheese5** [comment]
I'll add safety checks but this should not have happened.

**Comment by SwissCheese5** [comment]
Fixed in d18d1a1
