### ISSUE TITLE
Crash Upon Switching Pearls

### ISSUE THREAD

**Issue by Xenos93** [TeamWizardry/Wizardry#285]
Crash Log : 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Wizardry Plugin (Escapees-Wizardry-Mod-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22(1).jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2(1).jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0(2).jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.21.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.14.jar)
  Techguns Core (techguns-1.12.2-2.0.1.2_1.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 6/26/19 11:53 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:1005)
	at net.minecraft.client.gui.FontRenderer.func_78271_c(FontRenderer.java:996)
	at com.teamwizardry.wizardry.client.gui.pearlswap.GuiPearlSwap.renderText(GuiPearlSwap.java:592)
	at com.teamwizardry.wizardry.client.gui.pearlswap.GuiPearlSwap.renderCenteralCircle(GuiPearlSwap.java:578)
	at com.teamwizardry.wizardry.client.gui.pearlswap.GuiPearlSwap.lambda$new$1(GuiPearlSwap.java:145)
	at com.teamwizardry.wizardry.client.gui.pearlswap.GuiPearlSwap$$Lambda$15308/474696030.accept(Unknown Source)
	at com.teamwizardry.librarianlib.features.eventbus.EventBus.fire(EventBus.kt:30)
	at com.teamwizardry.librarianlib.features.eventbus.EventBus.fire(EventBus.kt:17)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler.draw(ComponentRenderHandler.kt:130)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:25)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRelationshipHandler.forEachChild(ComponentRelationshipHandler.kt:160)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler.draw(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:25)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRelationshipHandler.forEachChild(ComponentRelationshipHandler.kt:160)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler.draw(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:25)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRelationshipHandler.forEachChild(ComponentRelationshipHandler.kt:160)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler.draw(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.GuiBase.func_73863_a(GuiBase.kt:100)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:1005)
	at net.minecraft.client.gui.FontRenderer.func_78271_c(FontRenderer.java:996)
	at com.teamwizardry.wizardry.client.gui.pearlswap.GuiPearlSwap.renderText(GuiPearlSwap.java:592)
	at com.teamwizardry.wizardry.client.gui.pearlswap.GuiPearlSwap.renderCenteralCircle(GuiPearlSwap.java:578)
	at com.teamwizardry.wizardry.client.gui.pearlswap.GuiPearlSwap.lambda$new$1(GuiPearlSwap.java:145)
	at com.teamwizardry.wizardry.client.gui.pearlswap.GuiPearlSwap$$Lambda$15308/474696030.accept(Unknown Source)
	at com.teamwizardry.librarianlib.features.eventbus.EventBus.fire(EventBus.kt:30)
	at com.teamwizardry.librarianlib.features.eventbus.EventBus.fire(EventBus.kt:17)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler.draw(ComponentRenderHandler.kt:130)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:25)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRelationshipHandler.forEachChild(ComponentRelationshipHandler.kt:160)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler.draw(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:25)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRelationshipHandler.forEachChild(ComponentRelationshipHandler.kt:160)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler.draw(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler$draw$3.invoke(ComponentRenderHandler.kt:25)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRelationshipHandler.forEachChild(ComponentRelationshipHandler.kt:160)
	at com.teamwizardry.librarianlib.features.gui.component.supporting.ComponentRenderHandler.draw(ComponentRenderHandler.kt:173)
	at com.teamwizardry.librarianlib.features.gui.GuiBase.func_73863_a(GuiBase.kt:100)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)

-- Screen render details --
Details:
	Screen name: com.teamwizardry.wizardry.client.gui.pearlswap.GuiPearlSwap
	Mouse location: Scaled: (480, 269). Absolute: (960, 540)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['GalacticScarf'/47763, l='MpServer', x=1030.29, y=77.00, z=1249.87], EntityOtherPlayerMP['Siamakot'/322, l='MpServer', x=948.95, y=84.08, z=1248.02]]
	Chunk stats: MultiplayerChunkCache: 729, 729
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-148,64,256), Chunk: (at 12,4,0 in -10,16; contains blocks -160,0,256 to -145,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 415051 game time, 661 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 108 total; [EntitySpider['Araignée'/47873, l='MpServer', x=1090.97, y=24.00, z=1316.04], EntitySpider['Araignée'/47874, l='MpServer', x=1080.50, y=26.00, z=1316.50], ZombieSoldier['Zombie Soldier'/47620, l='MpServer', x=1045.50, y=60.00, z=1297.50], Bandit['Bandit'/47876, l='MpServer', x=1076.50, y=26.00, z=1322.50], EntityCow['Vache'/517, l='MpServer', x=1007.25, y=72.00, z=1301.82], EntitySheep['Mouton'/518, l='MpServer', x=995.70, y=76.00, z=1301.49], ZombieFarmer['Zombie Farmer'/47878, l='MpServer', x=1077.50, y=26.00, z=1320.50], EntityCow['Vache'/519, l='MpServer', x=1000.15, y=81.00, z=1302.53], EntityCow['Vache'/520, l='MpServer', x=992.72, y=87.00, z=1308.42], EntityCow['Vache'/524, l='MpServer', x=1010.21, y=76.00, z=1316.25], EntityPlayerSP['GalacticScarf'/47763, l='MpServer', x=1030.29, y=77.00, z=1249.87], EntityOtherPlayerMP['Siamakot'/322, l='MpServer', x=948.95, y=84.08, z=1248.02], EntityOffRoader['Off Roader'/530, l='MpServer', x=1008.00, y=71.00, z=1217.13], EntityCow['Vache'/534, l='MpServer', x=1021.66, y=71.00, z=1174.29], EntityChicken['Poule'/535, l='MpServer', x=1025.74, y=71.00, z=1173.13], EntityZombie['Zombie'/47645, l='MpServer', x=981.50, y=50.00, z=1304.50], EntityCow['Vache'/543, l='MpServer', x=1046.38, y=72.00, z=1313.84], EntityCow['Vache'/544, l='MpServer', x=1040.96, y=72.00, z=1324.39], EntityCow['Vache'/545, l='MpServer', x=1051.25, y=71.00, z=1314.40], EntitySkeleton['Squelette'/47650, l='MpServer', x=1020.50, y=22.00, z=1328.50], EntityCow['Vache'/546, l='MpServer', x=1034.83, y=72.00, z=1322.53], ZombieFarmer['Zombie Farmer'/47652, l='MpServer', x=1022.50, y=22.00, z=1325.50], EntitySpider['Araignée'/47911, l='MpServer', x=1044.50, y=24.00, z=1203.50], EntityBat['Chauve-souris'/47659, l='MpServer', x=1051.62, y=62.10, z=1274.41], EntityBat['Chauve-souris'/47660, l='MpServer', x=1006.82, y=26.10, z=1283.19], ZombieSoldier['Zombie Soldier'/47916, l='MpServer', x=999.50, y=36.00, z=1267.50], SkeletonSoldier['Skeleton Soldier'/47918, l='MpServer', x=1001.50, y=36.00, z=1269.50], EntityItem['item.item.egg'/47152, l='MpServer', x=1088.87, y=68.00, z=1213.84], ZombieMiner['Zombie Miner'/47920, l='MpServer', x=999.50, y=36.00, z=1270.50], ZombieFarmer['Zombie Farmer'/47922, l='MpServer', x=1098.50, y=33.00, z=1174.50], Bandit['Bandit'/47924, l='MpServer', x=1096.50, y=33.00, z=1181.50], EntityZombie['Zombie'/47670, l='MpServer', x=979.50, y=50.00, z=1303.50], EntityZombie['Zombie'/47674, l='MpServer', x=1026.24, y=11.00, z=1202.50], ZombieMiner['Zombie Miner'/47934, l='MpServer', x=1063.50, y=58.00, z=1284.50], ZombieFarmer['Zombie Farmer'/47936, l='MpServer', x=1042.50, y=24.00, z=1207.50], EntityOtherPlayerMP['Siamakot'/322, l='MpServer', x=948.95, y=84.08, z=1248.02], ZombieMiner['Zombie Miner'/47685, l='MpServer', x=1001.16, y=46.00, z=1241.50], EntityZombie['Zombie'/47687, l='MpServer', x=983.78, y=32.00, z=1176.37], EntityChicken['Poule'/591, l='MpServer', x=1088.49, y=68.00, z=1213.07], EntityCow['Vache'/594, l='MpServer', x=1080.51, y=71.00, z=1221.17], SkeletonSoldier['Skeleton Soldier'/47954, l='MpServer', x=1099.50, y=38.00, z=1247.50], EntityBat['Chauve-souris'/47699, l='MpServer', x=1003.75, y=40.10, z=1263.68], EntityBat['Chauve-souris'/47700, l='MpServer', x=985.30, y=44.95, z=1245.80], EntityCow['Vache'/601, l='MpServer', x=1080.99, y=71.00, z=1208.62], ZombieSoldier['Zombie Soldier'/47964, l='MpServer', x=954.74, y=46.00, z=1268.49], ZombieSoldier['Zombie Soldier'/47966, l='MpServer', x=961.50, y=48.00, z=1273.50], ZombieMiner['Zombie Miner'/47718, l='MpServer', x=1004.50, y=56.00, z=1322.50], EntityPig['Cochon'/374, l='MpServer', x=979.72, y=93.00, z=1316.63], ZombieFarmer['Zombie Farmer'/43895, l='MpServer', x=973.15, y=66.00, z=1228.53], EntityCreeper['Creeper'/47483, l='MpServer', x=997.83, y=36.00, z=1267.50], EntityCow['Vache'/635, l='MpServer', x=1084.92, y=72.00, z=1272.21], EntityPig['Cochon'/381, l='MpServer', x=970.52, y=95.00, z=1316.95], EntityBat['Chauve-souris'/47743, l='MpServer', x=1061.12, y=49.11, z=1252.44], EntitySheep['Mouton'/384, l='MpServer', x=989.66, y=78.00, z=1302.55], EntitySheep['Mouton'/385, l='MpServer', x=990.73, y=78.00, z=1302.42], EntitySheep['Mouton'/386, l='MpServer', x=983.44, y=90.00, z=1304.04], EntitySquid['Poulpe'/47234, l='MpServer', x=1048.50, y=62.00, z=1190.50], EntityCow['Vache'/387, l='MpServer', x=978.48, y=87.00, z=1299.17], EntitySheep['Mouton'/388, l='MpServer', x=982.46, y=82.00, z=1299.03], ZombieMiner['Zombie Miner'/47748, l='MpServer', x=1048.10, y=64.00, z=1272.38], ZombieFarmer['Zombie Farmer'/47750, l='MpServer', x=1047.50, y=61.00, z=1264.32], EntityCow['Vache'/391, l='MpServer', x=1001.84, y=78.00, z=1318.50], EntityCow['Vache'/392, l='MpServer', x=996.37, y=78.00, z=1325.31], ZombieMiner['Zombie Miner'/47752, l='MpServer', x=1048.75, y=64.00, z=1272.56], ZombieMiner['Zombie Miner'/48010, l='MpServer', x=964.96, y=44.00, z=1257.34], Bandit['Bandit'/48012, l='MpServer', x=965.28, y=46.00, z=1260.59], EntityCow['Vache'/653, l='MpServer', x=1107.04, y=66.00, z=1267.87], EntitySkeleton['Squelette'/48013, l='MpServer', x=969.23, y=44.00, z=1253.53], ZombieSoldier['Zombie Soldier'/48015, l='MpServer', x=1095.50, y=54.00, z=1257.50], EntityCow['Vache'/656, l='MpServer', x=1059.65, y=68.00, z=1321.20], EntityCow['Vache'/657, l='MpServer', x=1057.69, y=76.00, z=1320.15], EntityCow['Vache'/658, l='MpServer', x=1057.45, y=76.00, z=1318.55], EntitySheep['Mouton'/403, l='MpServer', x=988.49, y=93.00, z=1285.19], EntityItem['item.item.rottenFlesh'/46743, l='MpServer', x=1003.92, y=72.00, z=1210.36], ZombieFarmer['Zombie Farmer'/48023, l='MpServer', x=1015.50, y=24.00, z=1193.50], EntitySheep['Mouton'/412, l='MpServer', x=972.23, y=83.00, z=1284.34], EntitySheep['Mouton'/420, l='MpServer', x=953.55, y=79.00, z=1318.55], EntitySheep['Mouton'/421, l='MpServer', x=953.14, y=79.00, z=1317.45], EntityBat['Chauve-souris'/47781, l='MpServer', x=1066.45, y=51.92, z=1265.28], EntityBat['Chauve-souris'/48038, l='MpServer', x=958.73, y=47.12, z=1268.76], EntityBat['Chauve-souris'/48039, l='MpServer', x=983.21, y=46.12, z=1312.32], EntityBat['Chauve-souris'/48040, l='MpServer', x=994.45, y=47.10, z=1318.25], EntitySheep['Mouton'/425, l='MpServer', x=989.50, y=76.00, z=1295.73], EntityBat['Chauve-souris'/48041, l='MpServer', x=993.46, y=46.10, z=1316.69], EntityPig['Cochon'/426, l='MpServer', x=972.72, y=95.00, z=1310.47], EntitySquid['Poulpe'/47786, l='MpServer', x=1062.42, y=58.57, z=1191.60], EntityBat['Chauve-souris'/48042, l='MpServer', x=986.26, y=46.35, z=1314.50], EntitySquid['Poulpe'/47787, l='MpServer', x=1064.40, y=58.42, z=1195.52], EntitySquid['Poulpe'/47788, l='MpServer', x=1062.40, y=59.93, z=1193.90], EntitySheep['Mouton'/435, l='MpServer', x=962.82, y=82.00, z=1287.55], EntitySheep['Mouton'/436, l='MpServer', x=973.55, y=85.00, z=1293.28], EntitySheep['Mouton'/439, l='MpServer', x=950.53, y=85.00, z=1308.30], EntityPig['Cochon'/440, l='MpServer', x=958.65, y=83.00, z=1303.02], EntitySpider['Araignée'/47805, l='MpServer', x=1033.00, y=74.00, z=1204.77], EntityBat['Chauve-souris'/47807, l='MpServer', x=1045.53, y=40.28, z=1281.50], EntityBat['Chauve-souris'/47808, l='MpServer', x=1076.20, y=47.00, z=1324.28], EntityChicken['Poule'/449, l='MpServer', x=990.50, y=73.00, z=1181.87], EntityBat['Chauve-souris'/47811, l='MpServer', x=1000.32, y=48.09, z=1234.59], ZombieFarmer['Zombie Farmer'/48076, l='MpServer', x=1067.50, y=52.00, z=1266.50], ZombieFarmer['Zombie Farmer'/48078, l='MpServer', x=1067.50, y=52.00, z=1264.50], EntityZombie['Zombie'/47826, l='MpServer', x=988.50, y=38.00, z=1249.50], ZombieFarmer['Zombie Farmer'/47571, l='MpServer', x=1046.50, y=60.00, z=1295.50], EntityCreeper['Creeper'/47839, l='MpServer', x=1047.50, y=58.00, z=1304.50], EntitySquid['Poulpe'/47586, l='MpServer', x=1048.50, y=62.00, z=1188.50], EntityCreeper['Creeper'/47845, l='MpServer', x=996.50, y=50.00, z=1171.50], EntitySpider['Araignée'/47847, l='MpServer', x=1044.50, y=54.00, z=1312.50], EntityWisp['Feu-follet'/47852, l='MpServer', x=1028.98, y=32.00, z=1286.52], Bandit['Bandit'/47862, l='MpServer', x=1103.50, y=31.00, z=1201.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4297213768 bytes (4098 MB) / 6006243328 bytes (5728 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                            | Signature                                |
	|:------ |:-------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | obfuscate            | 0.2.6             | minecraft.jar                                     | None                                     |
	| LCHIJA | techguns_core        | 1.12.2-1.0        | minecraft.jar                                     | None                                     |
	| LCHIJA | uncraftingtable      | 1.8-beta6         | 1.12UncraftingTable-1.8-beta6.jar                 | None                                     |
	| LCHIJA | baubles              | 1.5.2             | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHIJA | biomesoplenty        | 7.0.1.2439        | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar     | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22(1).jar                      | None                                     |
	| LCHIJA | chisel               | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| LCHIJA | chiselsandbits       | 14.33             | chiselsandbits-14.33.jar                          | None                                     |
	| LCHIJA | extendedrenderer     | v1.0              | coroutil-1.12.1-1.2.27.jar                        | None                                     |
	| LCHIJA | coroutil             | 1.12.1-1.2.27     | coroutil-1.12.1-1.2.27.jar                        | None                                     |
	| LCHIJA | configmod            | v1.0              | coroutil-1.12.1-1.2.27.jar                        | None                                     |
	| LCHIJA | customnpcs           | 1.12              | CustomNPCs_1.12.2(09jul18).jar                    | None                                     |
	| LCHIJA | doggytalents         | 1.14.2.451        | DoggyTalents-1.12.2-1.14.2.451-universal.jar      | None                                     |
	| LCHIJA | dsurround            | 3.4.9.14          | DynamicSurroundings-1.12.2-3.4.9.14.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | presets              | 3.4.9.14          | DynamicSurroundings-1.12.2-3.4.9.14.jar           | None                                     |
	| LCHIJA | forgelin             | 1.8.3             | Forgelin-1.8.3.jar                                | None                                     |
	| LCHIJA | librarianlib         | 4.19.2            | librarianlib-1.12.2-4.19.2-release.jar            | None                                     |
	| LCHIJA | wizardry             | 0.10.2            | Escapees-Wizardry-Mod-1.12.2.jar                  | None                                     |
	| LCHIJA | extrabitmanipulation | 1.12.2-3.4.1      | ExtraBitManipulation-1.12.2-3.4.1.jar             | None                                     |
	| LCHIJA | zerocore             | 1.12.2-0.1.2.8    | zerocore-1.12.2-0.1.2.8.jar                       | None                                     |
	| LCHIJA | bigreactors          | 1.12.2-0.4.5.65   | ExtremeReactors-1.12.2-0.4.5.65.jar               | None                                     |
	| LCHIJA | fbp                  | 2.4.1             | FancyBlockParticles-1.12.x-2.4.1.jar              | None                                     |
	| LCHIJA | cfm                  | 6.2.0             | furniture-6.2.0-1.12.2.jar                        | None                                     |
	| LCHIJA | geolosys             | 2.2.6             | Geolosys-1.12.2-2.2.6.jar                         | None                                     |
	| LCHIJA | icbmclassic          | 1.12.2-3.3.0.63   | ICBM-classic-1.12.2-3.3.0b63.jar                  | None                                     |
	| LCHIJA | ic2                  | 2.8.109-ex112     | industrialcraft-2-2.8.109-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | jei                  | 4.15.0.269        | jei_1.12.2-4.15.0.269.jar                         | None                                     |
	| LCHIJA | malisiscore          | 1.12.2-6.4.0      | malisiscore-1.12.2-6.4.0(2).jar                   | None                                     |
	| LCHIJA | malisisdoors         | 1.12.2-7.3.0      | malisisdoors-1.12.2-7.3.0 (1).jar                 | None                                     |
	| LCHIJA | mcjtylib_ng          | 3.1.1             | mcjtylib-1.12-3.1.1.jar                           | None                                     |
	| LCHIJA | mw                   | 1.11.7.2          | mw-1.11.7.7_mc1.12.2(1).jar                       | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2t           | Pam's+HarvestCraft+1.12.2t.jar                    | None                                     |
	| LCHIJA | llibrary             | 1.7.18            | llibrary-1.7.18-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | dragonmounts         | 1.12.2-1.5.8      | Realm-of-The-Dragons-Mod-1.12.2.jar               | None                                     |
	| LCHIJA | sandro               | 1.3 BETA-2        | Redstone+++ver1.3+BETA-2.jar                      | None                                     |
	| LCHIJA | redstoneplusplus     | 1.3 BETA-2        | Redstone+++ver1.3+BETA-2.jar                      | None                                     |
	| LCHIJA | redstonepaste        | 1.7.5             | redstonepaste-mc1.12-1.7.5.jar                    | None                                     |
	| LCHIJA | shutters             | 1.12.2-1.0-pre    | Shutters-2.0-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | storagecabinet       | 1.0               | Storage-Cabinet-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | techguns             | 2.0.1.2           | techguns-1.12.2-2.0.1.2_1.jar                     | None                                     |
	| LCHIJA | thaumcraft           | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
	| LCHIJA | bspkrscore           | at_0.9            | TreeCapitator-Mod-1.12.jar                        | None                                     |
	| LCHIJA | treecapitator        | at_0.9            | TreeCapitator-Mod-1.12.jar                        | None                                     |
	| LCHIJA | vehicle              | 0.41.0            | vehicle-0.41.0-mc1.12.2.jar                       | None                                     |
	| LCHIJA | worldedit            | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCHIJA | worleycaves          | 1.3.0             | worleycaves-1.3.0.jar                             | None                                     |
	| LCHIJA | zombieawareness      | 1.12.1-1.11.16    | zombieawareness-1.12.1-1.11.16.jar                | None                                     |
	| LCHIJA | jurassicraft         | 2.1.20            | JurassiCraft-1.12.2-2.1.20.jar                    | None                                     |
	| LCHIJA | librarianliblate     | 4.19.2            | librarianlib-1.12.2-4.19.2-release.jar            | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Wizardry Plugin (Escapees-Wizardry-Mod-1.12.2.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22(1).jar)
  team.chisel.ctm.client.asm.CTMTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
weaponlib (mw-1.11.7.7_mc1.12.2(1).jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0(2).jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.21.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.14.jar)
  org.blockartistry.DynSurround.asm.Transformer
Techguns Core (techguns-1.12.2-2.0.1.2_1.jar)
  techguns.core.TechgunsASMTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13559 Compatibility Profile Context 26.20.12001.7006' Renderer: 'Radeon RX 580 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: Radeon RX 580 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12001.7006, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz

**Comment by SwissCheese5** [comment]
Don't get your mod jar from anywhere other than curseforge.com
Delete all your mods and download them from there please, your jars have been downloaded from an illegal source and are subject to viruses
