### ISSUE TITLE
Crash when joining custom dimension

### ISSUE THREAD

**Issue by Darkere** [TeamWizardry/Wizardry#287]
People are crashing when joining our custom Advanced Rocketry dimension.

https://pastebin.com/rJCuWB9Q

Currently holding some players base hostage. Any ideas for a quick fix?

planet definition:
```
 <planet name="Asgard" DIMID="34">
            <isKnown>false</isKnown>
            <fogColor>1.0,1.0,1.0</fogColor>
            <skyColor>0.37350494,0.9763119,1.0</skyColor>
            <gravitationalMultiplier>130</gravitationalMultiplier>
            <orbitalDistance>127</orbitalDistance>
            <orbitalPhi>-4</orbitalPhi>
            <rotationalPeriod>10923</rotationalPeriod>
            <atmosphereDensity>41</atmosphereDensity>
            <biomeIds>biomesoplenty:undergarden,biomesoplenty:woodland,biomesoplenty:visceral_heap,minecraft:mutated_mesa,traverse:temperate_rainforest</biomeIds>
        </planet>

```

**Comment by FallenEagle1** [comment]
For some context, this is running All the Mods Remix 1.3.2.
Forge: 2838
Wizardry: 0.10.8

**Comment by Darkere** [comment]
Downgrading all the way down to 0.9.9 fixed the issue.

**Comment by SwissCheese5** [comment]
Seems like an incompatibility with thaumcraft?

**Comment by Darkere** [comment]
I'm reading that as thaumcraft looking up the biome type of each biome in the dictionary. Since it's using forge methods for that I would blame the people adding unregistered biomes to the dictionary. 

What I don't get is why it only happens in that dimension?

**Comment by SwissCheese5** [comment]
I'm unsure...

**Comment by murapix** [comment]
It gets weirder - that biome is and has been registered for several versions

**Comment by Darkere** [comment]
Oh, I know. We hadn't updated in a long time. 0.9.9 is what we were on before.

**Comment by SwissCheese5** [comment]
I think i know the problem.
We changed how our biomes register to a more up to standards method and I suppose our old biome exists in the world file still but unregistered and thaumcraft isn't checking if it's null/registered or not

**Comment by Darkere** [comment]
In that case, a fresh world wouldn't be affected. 

Just tested this, it freezes immediatly and spits out the error for cofh world too. 

https://pastebin.com/mw4d0qLx

Full Log: https://gist.githubusercontent.com/Darkere/84198cdb73e24638b323dae48ba48fc5/raw/1b0eaee3e7bb34bfdc6f6ba372c13d3641612541/gistfile1.txt

**Comment by Darkere** [comment]
Uh any chance you guys are using DIMID 34 for torikki?

**Comment by SwissCheese5** [comment]
What world type are you using

**Comment by Darkere** [comment]
Yep default is 34... Thank you for your time

Gonna check if changing that fixes it and close then.

**Comment by Darkere** [comment]
Alright, your dimension ID config isn't working but I'm gonna make a separate issue for that. 

After changing the dimID for the planet I can now go there without a problem. Your dimension is still crashing but I can live with that ;).

**Comment by SwissCheese5** [comment]
The dimension is incomplete (WIP) but sorry for the inconvenience
