### ISSUE TITLE
Crashing with Mohist Server

### ISSUE THREAD

**Issue by ryan1161** [TeamWizardry/Wizardry#293]
Mod version: wizardry-0.10.8.jar

After removing your mod my server started. Can you please find a fix as I would love to use this mod again on my server.

Link to Mohist issue on github: https://github.com/PFCraft/Mohist/issues/164

Link to Mohist: https://www.mohist.red/

[logs.zip](https://github.com/TeamWizardry/Wizardry/files/3461765/logs.zip)

**Comment by SwissCheese5** [comment]
This is not an issue with wizardry. This is an issue with most mod behavior against mohist. It's incompatible

**Comment by Mgazul** [comment]
Already fixed in Mohist
