### ISSUE TITLE
Spell Bug

### ISSUE THREAD

**Issue by jluck676** [TeamWizardry/Wizardry#294]
I'm playing All the Mods 3 and when I place a staff that contains a spell into my internal crafting area, it will remove the spell from the staff. This happens when I don't even complete the recipe where I remove the pearl from the staff. Once placed in the crafting area it removes the spell and I am left with a staff with a normal pearl in it

**Comment by SwissCheese5** [comment]
Update the mod, try again.

**Comment by PhotonChaos** [comment]
This seems to have been fixed. If you are still having this issue with the newest version of Wizardry and LibLib, please comment on this issue.
