### ISSUE TITLE
Cross compat issue with Bewitchment

### ISSUE THREAD

**Issue by Sunconure11** [TeamWizardry/Wizardry#295]
https://github.com/Um-Mitternacht/Bewitchment/issues/373

**Comment by SwissCheese5** [comment]
that's... weird

**Comment by SwissCheese5** [comment]
can you post ur latest.log in pastebin and show us please?

**Comment by Sunconure11** [comment]
@technomysterio

**Comment by TechnoMysterio** [comment]
Created a world, placed an Oven down and put fuel in, where it made charcoal:
[latest.log](https://github.com/TeamWizardry/Wizardry/files/3463729/latest.log)

**Comment by murapix** [comment]
If you remove Wizardry, but leave LibLib in, does this still happen? And if so, try the same with *just* Forgelin.

And finally, I do want to confirm, this was tested with only Bewitchment, Wizardry, and their respective dependencies?

**Comment by TechnoMysterio** [comment]
I tested that a while back, and this bug only happens when I have all three of Forgelin, LibLib and Wizardry installed. And the bug is still present even with only Bewitchment, Wizardry and the assorted dependencies installed.

**Comment by PhotonChaos** [comment]
Looks like this was a LibLib issue, but it's been fixed. Thanks for reporting!
