### ISSUE TITLE
stuck infinitely loading  in loading terrain screen after jumping into the void to get home from Unicorn dimension 

### ISSUE THREAD

**Issue by mightyjaffa12** [TeamWizardry/Wizardry#297]
as put in title went into the dimension with unicorns in it and when i jumped off the edge to come home it put me in an infinite dirt loading screen that im currently stuck in on my server my friend is also stuck, after about 5  mins of this the server kicks us

**Comment by SwissCheese5** [comment]
Can you reenter the server? What version of the mod are you on?

**Comment by mightyjaffa12** [comment]
running on the most up to date version on 1.12.2. Im able to enter the server but i am stuck in the loading terrain screen coming back from the dimension

**Comment by SwissCheese5** [comment]
What version

**Comment by mightyjaffa12** [comment]
as i said lasted version witch means 0.10.8

**Comment by forcemagic** [comment]
Can confirm the issue, on the latest version. FML continuously loads & unloads the dimension 33, and the player experiences continuous dimension travel back and forth.

Wizardry version: 0.10.8
Forge: 14.23.5.2838

**Comment by mightyjaffa12** [comment]
I managed to get out by deleting the player data from the world so it resets your position you of course lose all your items but hay ho :l

**Comment by SwissCheese5** [comment]
you could have changed ur dimension is using an nbt editor, but we will need to investigate further since this is a very complicated problem we can't reproduce

**Comment by thecodewarrior** [comment]
My brother just ran into it too :P

**Comment by thecodewarrior** [comment]
As a temporary workaround, having someone else run `/kill YourUsername` in the 30 seconds before you time out fixes it.

**Comment by PhotonChaos** [comment]
Unfortunately, we can't reliably reproduce this issue, so we can't fix it. If you have COFH core installed you can use `/cofh tpx <player> 0`, to TP a player to the overworld. `/kill`-ing the player also works, or NBT editing the dimension.

If anyone can reliably reproduce this in the newest version of wizardry, please comment on this issue.
