### ISSUE TITLE
Hitbox bugs

### ISSUE THREAD

**Issue by Alucabr** [TeamWizardry/Wizardry#300]
every projectile spell I create has a hitbox bugged, even creating the simplest spell.

**Comment by SwissCheese5** [comment]
.... Pics?

**Comment by murapix** [comment]
"hitbox bugged" could mean just about anything, this tells us nothing

**Comment by PhotonChaos** [comment]
Please comment more info on steps to reproduce this bug, or more details on which ones are bugged.
