### ISSUE TITLE
Crash on complex spell usage

### ISSUE THREAD

**Issue by Triking66** [TeamWizardry/Wizardry#301]
Crafted a decently complex spell...
Projectile
> Gravity Well
>> Zone
>>> Spell that on kill, deals damage to all nearby entities (can't remember by name)

Had some modifiers as well, but I can't remember what all was on them, or what levels they had.
Can't check either, world is unopenable.

Crash: Deserialization of Null object.

Crash log is available.
[crash-2019-08-13_19.33.00-server.txt](https://github.com/TeamWizardry/Wizardry/files/3499433/crash-2019-08-13_19.33.00-server.txt)

**Comment by murapix** [comment]
You need to update, this was fixed long ago
