### ISSUE TITLE
Server Crash on Spell Cast [Players Cannot Join Server]

### ISSUE THREAD

**Issue by CaidenTheJust** [TeamWizardry/Wizardry#302]
Good morning!

One of my players crafted a spell with Projectile -> Area -> Ice.
When casting, the server crashed.
Now when players attempt to join, the server shuts down.

Here is the crash log from actually casting the spell.
[https://pastebin.com/857wE8um](https://pastebin.com/857wE8um)

Here is the log from when a player tries to join the server after casting. It instantly kicks them and restarts the server.
[https://pastebin.com/qU03mvEg](https://pastebin.com/qU03mvEg)

**Comment by PhotonChaos** [comment]
Thank you for reporting! This has just been fixed!
