### ISSUE TITLE
Persistent FPS loss when creating spells

### ISSUE THREAD

**Issue by lyko555** [TeamWizardry/Wizardry#305]
I am using ATM 3 with the 10.8  release of wizardry.

When i create spells using high multiples of components I get an instant FPS drop from 200+   down to 54  if i create another spell  it will continue to drop  24 then 12 to eventually 4fps
this persists until i completely close out the client and restart.  The server Admin said the server was not showing any change.
 
https://gist.github.com/lyko555/53bfc3189a813c7861805fa3855a7776

**Comment by mild-prowler** [comment]
I am also experiencing the same issue. A look into this would be appreciated.

**Comment by SwissCheese5** [comment]
As  temporary solution, break and replace the crafting plate and it'll fix itself.

**Comment by PhotonChaos** [comment]
This happened to me as well. 

Try removing optifine if you have that installed, this fixed the issue for me.

**Comment by PhotonChaos** [comment]
I think the issue may have been fixed. If anyone is still experiencing this issue with the new version of wizardry (0.11.0, coming soon), _and_ LibLib, please leave a comment on this issue.
