### ISSUE TITLE
Problems with traveling to unicorn realm

### ISSUE THREAD

**Issue by KaCKoMaHa** [TeamWizardry/Wizardry#306]
So, we generated the server without having the wizardry mod and we added the mod later. Jumping from >140 blocks to bedrock doesn't make the travel to the other dimension work. Where can we find the setting which indicates if the realm is active on server(our server), if it is generated, and if not - how to generate it afterwards?

**Comment by PhotonChaos** [comment]
The Underworld should be enabled by default and should generate on entry. Make sure that you are jumping without any sort of fall protection such as flight or slime boots. Make sure you update Wizardry and LibLib, and if the issue still persists comment on this issue with steps to reproduce it, as well as a mod list and a google drive link to the config folder so we can try and figure out the issue. Also, let us know if you are using plugins if it happens again. All settings should be in the Wizardry config file.
