### ISSUE TITLE
Phase Effect not working properly

### ISSUE THREAD

**Issue by Sourpowerpete** [TeamWizardry/Wizardry#31]
https://gfycat.com/UncomfortablePointlessChihuahua

**Comment by LordSaad44** [comment]
Even with the newest jar I gave you?

**Comment by Sourpowerpete** [comment]
Yes, i'm using the "kill yourself" jar

**Comment by LordSaad44** [comment]
@Sourpowerpete i already gave you a "phase works i promise" jar after that. try that. You must've skipped over it.
