### ISSUE TITLE
"Floaty Water" Levitation Issue

### ISSUE THREAD

**Issue by Giminar** [TeamWizardry/Wizardry#310]
I was pointed to this mod author for an issue regarding the "floaty water" in the modpack for 12.2.2. Sometimes when falling into the water, it will occasionally trap us in a weird "flight mode". We can't elevate or lower ourselves in any way other than teleporting, but once arriving at our destination, we still can't do either once again. The only solution has been to relog, which becomes troublesome. 

I just wanted to make you aware of what we've discovered. 

We were given the modpack through "All the Mods 3". We're playing on Windows 10. All characters were cycled through creative and other modes to see if we could reproduce it, and regardless of what mode, we found that it would still happen. It appears to be a random occurrence.

**Comment by SwissCheese5** [comment]
Update the mod. We provide slight elevation now.

**Comment by Giminar** [comment]
Thank you
