### ISSUE TITLE
Randomly spawned in the Underworld

### ISSUE THREAD

**Issue by DTGitRepository** [TeamWizardry/Wizardry#315]
I would appreciate this if I had started interacting with Wizardry elements but I haven't touched this mod previously yet when I logged in earlier, I spawned in the Underworld for some reason. Had no idea how to get out so ended up teleporting away from those immortal-no-clip-mega-attack-speed-wraith-things using JourneyMap waypoints.

Can't imagine this is intentional(?)

**Comment by PhotonChaos** [comment]
That's unfortunate, but there's not enough info in this post for us to fix the issue. To exit the underworld, you can fall into the void. The wraiths aren't totally unkillable.

If you are able to give us some more info on how to reproduce this effect, please comment on this issue and we'll try and fix it. Make sure you have the latest version of Wizardry and LibLib.
