### ISSUE TITLE
Crash in loading minecraft

### ISSUE THREAD

**Issue by AngelRed** [TeamWizardry/Wizardry#316]
Hi, my minecraft is crashing when i launching the game, i know the crash is about the dimension ID, i tried to change it in config files, but that doesn't change nothing (the problem in crash report said it's the dimension id 34 already taken), so i tried in config files, but keep crashing and telling it's the dimension id already taken (34).
I tried to change it at 235 and 2034, nothing change always the same crash report... Can you help me figure it out ? It with any dimension mod (without the game work, or without wizardry and with any dimension, anyway, it's a if conflict between those mods)

Crash report in case : 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  HCASM (HammerCore-1.12.2-2.0.5.7.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  McLib core mod (mclib-1.0.2-1.12.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FutureMC (future-mc-0.1.13.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  Wizardry Plugin (wizardry-0.10.8.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 2/8/20 12:52 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wizardry (wizardry)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 34, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at com.teamwizardry.wizardry.proxy.CommonProxy.preInit(CommonProxy.java:81)
	at com.teamwizardry.wizardry.proxy.ClientProxy.preInit(ClientProxy.java:50)
	at com.teamwizardry.wizardry.Wizardry.preInit(Wizardry.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 430667024 bytes (410 MB) / 2650800128 bytes (2528 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2846 Optifine OptiFine_1.12.2_HD_U_E3 116 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                              | Version                  | Source                                             | Signature                                |
	|:----- |:------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                       | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCH   | mcp                             | 9.42                     | minecraft.jar                                      | None                                     |
	| LCH   | FML                             | 8.0.99.99                | forge-1.12.2-14.23.5.2846.jar                      | None                                     |
	| LCH   | forge                           | 14.23.5.2846             | forge-1.12.2-14.23.5.2846.jar                      | None                                     |
	| LCH   | futuremccore                    | 0.1.12                   | minecraft.jar                                      | None                                     |
	| LCH   | uncraftingtable                 | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6.jar                | None                                     |
	| LCH   | actuallyadditions               | 1.12.2-r151              | ActuallyAdditions-1.12.2-r151-2.jar                | None                                     |
	| LCH   | any_dimension_mod               | 1.3.4                    | any_dimension_mod_v1.3.4.jar                       | None                                     |
	| LCH   | jei                             | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LCH   | appleskin                       | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
	| LCH   | crafttweaker                    | 4.1.15                   | CraftTweaker2-1.12-4.1.15.jar                      | None                                     |
	| LCH   | mantle                          | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCH   | ccm                             | 1.0                      | ccm-1.0.jar                                        | None                                     |
	| LCH   | ctm                             | MC1.12.2-1.0.1.30        | CTM-MC1.12.2-1.0.1.30.jar                          | None                                     |
	| LCH   | chisel                          | MC1.12.2-1.0.1.44        | Chisel-MC1.12.2-1.0.1.44.jar                       | None                                     |
	| LCH   | quark                           | r1.6-177                 | Quark-r1.6-177.jar                                 | None                                     |
	| LCH   | twilightforest                  | 3.9.984                  | twilightforest-1.12.2-3.9.984-universal.jar        | None                                     |
	| LCH   | tconstruct                      | 1.12.2-2.13.0.171        | TConstruct-1.12.2-2.13.0.171.jar                   | None                                     |
	| LCH   | conarm                          | 1.2.5.1                  | conarm-1.12.2-1.2.5.1.jar                          | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | armoryexpansion                 | 1.4.1                    | armoryexpansion-1.4.1.jar                          | None                                     |
	| LCH   | armoryexpansion-custommaterials | 1.4.1                    | armoryexpansion-1.4.1.jar                          | None                                     |
	| LCH   | llibrary                        | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire                      | 1.8.0                    | iceandfire-1.8.0.jar                               | None                                     |
	| LCH   | armoryexpansion-iceandfire      | 1.4.1                    | armoryexpansion-1.4.1.jar                          | None                                     |
	| LCH   | armoryexpansion-matteroverdrive | 1.4.1                    | armoryexpansion-1.4.1.jar                          | None                                     |
	| LCH   | autocrafter                     | 4.3                      | autocrafter-4.3.jar                                | None                                     |
	| LCH   | autoreglib                      | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCH   | backpack                        | 3.0.2                    | backpack-3.0.2-1.12.2.jar                          | None                                     |
	| LCH   | mmdlib                          | 1.0.0-rc2                | MMDLib-1.12-1.0.0-rc2.36.jar                       | None                                     |
	| LCH   | basemetals                      | 2.5.0-rc2                | BaseMetals-1.12-2.5.0-rc2.332.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | baubles                         | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | forgelin                        | 1.8.3                    | Forgelin-1.8.3.jar                                 | None                                     |
	| LCH   | betterportals                   | 0.3.5                    | betterportals-0.3.5.jar                            | None                                     |
	| LCH   | blockcraftery                   | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                     | None                                     |
	| LCH   | buildinggadgets                 | 2.7.3                    | BuildingGadgets-2.7.3.jar                          | None                                     |
	| LCH   | chameleon                       | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCH   | codechickenlib                  | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | chickenchunks                   | 2.4.1.73                 | ChickenChunks-Mod-1.12.2.jar                       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux                    | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore                        | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
	| LCH   | cofhworld                       | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cosmeticarmorreworked           | 1.12.2-v4a               | CosmeticArmorReworked-1.12.2-v4a.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCH   | ctgui                           | 1.0.0                    | CraftTweaker2-1.12-4.1.15.jar                      | None                                     |
	| LCH   | crafttweakerjei                 | 2.0.2                    | CraftTweaker2-1.12-4.1.15.jar                      | None                                     |
	| LCH   | cucumber                        | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
	| LCH   | customspawner                   | 3.11.3                   | CustomMobSpawner-3.11.3.jar                        | None                                     |
	| LCH   | cxlibrary                       | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                         | None                                     |
	| LCH   | ptrmodellib                     | 1.0.4                    | PTRLib-1.0.4.jar                                   | None                                     |
	| LCH   | props                           | 2.6.2                    | Decocraft-2.6.2_1.12.2.jar                         | None                                     |
	| LCH   | doggytalents                    | 1.14.2.396               | DoggyTalents-1.12.2-1.14.2.396-universal.jar       | None                                     |
	| LCH   | mocreatures                     | 12.0.3                   | DrZharks MoCreatures Mod-12.0.3.jar                | None                                     |
	| LCH   | eleccore                        | 1.9.452                  | ElecCore-1.12.2-1.9.452.jar                        | None                                     |
	| LCH   | elevatorid                      | 1.3.11                   | ElevatorMod-1.12.2-1.3.11.jar                      | None                                     |
	| LCH   | extrautils2                     | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCH   | simplecore                      | 1.7.3.4                  | simplecore-1.12.2-1.7.3.4.jar                      | None                                     |
	| LCH   | simpleores                      | 1.11.2.2                 | simpleores-1.12.2-1.11.2.2.jar                     | None                                     |
	| LCH   | thermalfoundation               | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | fusion                          | 2.4.1.11                 | fusion-1.12.2-2.4.1.11.jar                         | None                                     |
	| LCH   | minecraftfuture                 | 0.1.13                   | future-mc-0.1.13.jar                               | None                                     |
	| LCH   | gravestone                      | 1.10.3                   | gravestone-1.10.3.jar                              | None                                     |
	| LCH   | hammercore                      | 2.0.5.7                  | HammerCore-1.12.2-2.0.5.7.jar                      | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCH   | harvest                         | 1.12-1.2.6-18            | Harvest-1.12-1.2.6-18.jar                          | None                                     |
	| LCH   | huds                            | #VERSION#                | Huds-1.12.2-1.0.3.jar                              | None                                     |
	| LCH   | waila                           | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCH   | teslacorelib                    | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | industrialforegoing             | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
	| LCH   | mysticalagriculture             | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar               | None                                     |
	| LCH   | harvestcraft                    | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2ze.jar                    | None                                     |
	| LCH   | rustic                          | 1.1.1                    | rustic-1.1.1.jar                                   | None                                     |
	| LCH   | integrationforegoing            | 1.12.2-1.9               | IntegrationForegoing-1.12.2-1.9.jar                | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCH   | inventorytweaks                 | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironchest                       | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCH   | itemfilters                     | 1.0.3.12                 | ItemFilters-1.0.3.12.jar                           | None                                     |
	| LCH   | jehc                            | 1.6.4                    | jehc-1.12.2-1.6.4.jar                              | None                                     |
	| LCH   | librarianlib                    | 4.20                     | librarianlib-1.12.2-4.20-release.jar               | None                                     |
	| LCH   | mclib                           | 1.0.2                    | mclib-1.0.2-1.12.2.jar                             | None                                     |
	| LCH   | metallurgy                      | 0.2.3                    | Metallurgy-4-Reforged-0.2.3.jar                    | None                                     |
	| LCH   | metamorph                       | 1.1.8                    | metamorph-1.1.8-1.12.2.jar                         | None                                     |
	| LCH   | mtrm                            | 1.2.2.30                 | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar         | None                                     |
	| LCH   | minions                         | 2.0.3                    | Minions-1.12.2.jar                                 | None                                     |
	| LCH   | modernmetals                    | 2.5.0-rc2                | ModernMetals-1.12-2.5.0-rc2.152.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | morefurnaces                    | 1.10.5                   | MoreFurnaces-1.12.2-1.10.6.jar                     | None                                     |
	| LCH   | shear                           | 1.1.2                    | MoreShearables1.3.1-1.12.2.jar                     | None                                     |
	| LCH   | netherportalfix                 | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar                  | None                                     |
	| LCH   | nutrition                       | 4.4.0                    | Nutrition-1.12.2-4.4.0.jar                         | None                                     |
	| LCH   | orespawn                        | 3.3.1                    | OreSpawn-1.12-3.3.1.172.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | plustic                         | 7.1.6.1                  | plustic-7.1.6.1.jar                                | None                                     |
	| LCH   | qsilkspawners                   | 1.1.2                    | qsilkspawners-1.1.2.jar                            | None                                     |
	| LCH   | radixcore                       | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar               | None                                     |
	| LCH   | roguelike                       | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| LCH   | simplequarry                    | 27r                      | SimpleQuarry-1.12.2-27r.jar                        | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCH   | simpletcon                      | 3.0                      | SimpleTcon-3.0a.jar                                | None                                     |
	| LCH   | speedyhoppers                   | 1.1.19                   | speedyhoppers-1.1.19.jar                           | None                                     |
	| LCH   | stacksize                       | 1.1                      | stacksize-1.12.2-1.0.jar                           | None                                     |
	| LCH   | storagedrawers                  | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0.jar                    | None                                     |
	| LCH   | subcommonlib                    | 1.2.0.1                  | subcommonlib-sublib-1.12.2-1.2.0.4.jar             | None                                     |
	| LCH   | taiga                           | 1.12.2-1.3.3             | taiga-1.12.2-1.3.4.jar                             | None                                     |
	| LCH   | telepads                        | $version                 | telepads-1.12.2-1.1.0.5.jar                        | None                                     |
	| LCH   | thermalexpansion                | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | thermaldynamics                 | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | tinkersjei                      | 1.2                      | tinkersjei-1.2.jar                                 | None                                     |
	| LCH   | tinkertoolleveling              | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCH   | uppers                          | 0.0.6                    | Uppers-0.0.6.jar                                   | None                                     |
	| LCE   | wizardry                        | 0.10.8                   | wizardry-0.10.8.jar                                | None                                     |
	| LC    | worldedit                       | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar  | None                                     |
	| LC    | xaerominimap                    | 1.16                     | Xaeros_Minimap_FP1.16_Forge_1.12.jar               | None                                     |
	| LC    | xpfromharvest                   | 1.1.0                    | xpfromharvest-1.12.2-1.1.0.jar                     | None                                     |
	| LC    | xpholder                        | 2.0.4                    | XpHolder-2.0.4-mc1.12.x.jar                        | None                                     |
	| LC    | structurize                     | 1.12.2-0.10.198-ALPHA    | structurize-1.12.2-0.10.198-ALPHA.jar              | None                                     |
	| LC    | minecolonies                    | 1.12.2-0.10.679-RELEASE  | minecolonies-1.12.2-0.10.679-RELEASE-universal.jar | None                                     |
	| LC    | armoryexpansion-conarm          | 1.4.1                    | armoryexpansion-1.4.1.jar                          | None                                     |
	| LC    | eleccoreloader                  | 1.9.452                  | ElecCore-1.12.2-1.9.452.jar                        | None                                     |
	| LC    | librarianliblate                | 4.20                     | librarianlib-1.12.2-4.20-release.jar               | None                                     |
	| LC    | mysticallib                     | 1.12.2-1.3.1             | mysticallib-1.12.2-1.3.1.jar                       | None                                     |
	| LC    | teslacorelib_registries         | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |
	| UD    | mclib_core                      | 1.0.2                    | minecraft.jar                                      | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
HCASM (HammerCore-1.12.2-2.0.5.7.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
McLib core mod (mclib-1.0.2-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
FutureMC (future-mc-0.1.13.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Wizardry Plugin (wizardry-0.10.8.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	HammerCore Debug Information: 
Dependent Mods:
    -Simple Quarry (simplequarry) @27r

	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 432.00
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by SwissCheese5** [comment]
The dimension id is conflicting with some other mod. go to wizardry's config file and change the dimension id to something random. if it crashes again, keep trying different IDs because some mods you have are already using the same Id you chose

**Comment by AngelRed** [comment]
I already did what you say, but the error message still the same with the same id

**Comment by AngelRed** [comment]
I mean, i change and save the different id (34 to 2034 or 235) and it still the same id error
So there are something to confirm about change of this id?

**Comment by murapix** [comment]
Ok, I see what's happened here. The latest published version does not have the dimension paying attention to the config value, as that change was made a little over a month later. You'll have to go look through your other mods to see what else is trying to use dimension 34, and change *that* instead.

**Comment by AngelRed** [comment]
Alright thanks!

**Comment by AngelRed** [comment]
i think it's any dimension mods, but i tried to delete wizardry (temporary) to load config files of any dimension, but i don't see those config files, tried to search in too, so i don't know what to do to change those ids... :x
