### ISSUE TITLE
Crashes with alternate java version

### ISSUE THREAD

**Issue by Geckoleon** [TeamWizardry/Wizardry#318]
Hi, 
I've been using an alternate java version then the one packaged with minecraft as I found it tends to run better with the large amounts of mods I have normally - AdoptOpenJDK - and for some reason, this mod crashes instantly if I have the book out with that java version, but works perfectly fine with the stock java version
tested it with only this mod+its dependencies installed, crashes every time I take the book out, instantly
[debug.log](https://github.com/TeamWizardry/Wizardry/files/4406377/debug.log)

**Comment by murapix** [comment]
That log unfortunately shows nothing wrong, it just cuts off at the end where I assume the error happens. We'll need the actual error in order to tell anything, although I can't guarantee we'll really do anything about it due to you not using a standard jdk

**Comment by Geckoleon** [comment]
I tried leaving it to do nothing for a long time, but that's all it does - just crashes as soon as I take the book out, and that's what the logs end up like - if I try it with vanillafix so it should display crashes, it instead hangs indefinitely until I force quit it with task manager - is there any other way I could force a log to occur?

**Comment by murapix** [comment]
Not that I know of, it's the jdk itself that's crashing. There's likely nothing you could do in minecraft that would change it

**Comment by Geckoleon** [comment]
well, alright then - in that case I guess I'll try it again if an update comes out and see if it no longer crashes - would love to use this mod as it's so fun to make your own spells but the stock jdk just doesn't run well enough with the number of mods I have compared to this one
thanks for your help anyways!

**Comment by Geckoleon** [comment]
Did a little bit more looking around and I managed to find a full output log and found the relevant crash info
https://pastebin.com/VQeHWWrY

**Comment by SwissCheese5** [comment]
OpenJ9 has very little support and has issues with several other mods. Change it.
