### ISSUE TITLE
Minecraft ran into a problem - using magic spells dont work

### ISSUE THREAD

**Issue by Lavdrim18** [TeamWizardry/Wizardry#319]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2020-04-11 18:42:18 CEST
Description: Error executing task

java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
    at electroblob.wizardry.spell.CureEffects.applyEffects(CureEffects.java:25)
    at electroblob.wizardry.spell.SpellBuff.cast(SpellBuff.java:113)
    at electroblob.wizardry.item.ItemWand.cast(ItemWand.java:423)
    at electroblob.wizardry.item.ItemWand.onItemRightClick(ItemWand.java:353)
    at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:217)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClick(PlayerInteractionManager.java:358)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItem(NetHandlerPlayServer.java:765)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:32)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:9)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1675863800 bytes (1598 MB) / 6509559808 bytes (6208 MB) up to 7516192768 bytes (7168 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 8, allocated: 20, tallocated: 86
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 40 mods loaded, 40 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                     | Version                 | Source                                             | Signature                                |
       |:------ |:---------------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft              | 1.12.2                  | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                    | 9.42                    | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                    | 8.0.99.99               | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | forge                  | 14.23.5.2847            | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | micdoodlecore          |                         | minecraft.jar                                      | None                                     |
       | LCHIJA | battletowers           | 1.6.5                   | BattleTowers-1.12.2.jar                            | None                                     |
       | LCHIJA | biomesoplenty          | 7.0.1.2444              | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
       | LCHIJA | guideapi               | 1.12-2.1.8-63           | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
       | LCHIJA | bloodmagic             | 1.12.2-2.4.1-103        | BloodMagic-1.12.2-2.4.1-103.jar                    | None                                     |
       | LCHIJA | bookworm               | 1.12.2-2.5.1            | bookworm-1.12.2-2.5.1.jar                          | None                                     |
       | LCHIJA | chameleon              | 1.12-4.1.3              | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | LCHIJA | cucumber               | 1.1.3                   | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
       | LCHIJA | doggytalents           | 1.15.1.4                | DoggyTalents-1.12.2-1.15.1.4-universal.jar         | None                                     |
       | LCHIJA | dragon_enchants        | 1.0                     | dragonenchantments-0.0.4.jar                       | None                                     |
       | LCHIJA | ebwizardry             | 4.2.10                  | ElectroblobsWizardry-4.2.10-MC1.12.2.jar           | None                                     |
       | LCHIJA | forgelin               | 1.8.2                   | Forgelin-1.8.2.jar                                 | None                                     |
       | LCHIJA | llibrary               | 1.7.19                  | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | fossil                 | 8.0.4                   | fossilsarcheology-8.0.4.jar                        | None                                     |
       | LCHIJA | cfm                    | 6.3.1                   | furniture-6.3.1-1.12.2.jar                         | None                                     |
       | LCHIJA | galacticraftcore       | 4.0.1.181               | GalacticraftCore-1.12.2-4.0.1.181.jar              | None                                     |
       | LCHIJA | galacticraftplanets    | 4.0.1.181               | Galacticraft-Planets-1.12.2-4.0.1.181.jar          | None                                     |
       | LCHIJA | iceandfire             | 1.8.4                   | iceandfire-1.8.4.jar                               | None                                     |
       | LCHIJA | ichunutil              | 7.2.2                   | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | jei                    | 4.15.0.291              | jei_1.12.2-4.15.0.291.jar                          | None                                     |
       | LCHIJA | librarianlib           | 4.19.2                  | librarianlib-1.12.2-4.19.2-release.jar             | None                                     |
       | LCHIJA | morph                  | 7.1.3                   | Morph-1.12.2-7.1.3.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | mowziesmobs            | 1.5.4                   | mowziesmobs-1.5.4.jar                              | None                                     |
       | LCHIJA | patchouli              | 1.0-20                  | Patchouli-1.0-20.jar                               | None                                     |
       | LCHIJA | somanyenchantments     | 0.4.4                   | So Many Enchantments V0.4.4.jar                    | None                                     |
       | LCHIJA | twilightforest         | 3.10.1013               | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | LCHIJA | tfspellpack            | 1.0                     | TFSpellPack-1.0-MC1.12.2.jar                       | None                                     |
       | LCHIJA | vampirism              | 1.6.2                   | Vampirism-1.12.2-1.6.2.jar                         | None                                     |
       | LCHIJA | teamlapen-lib          | 1.6.2                   | Vampirism-1.12.2-1.6.2.jar                         | None                                     |
       | LCHIJA | vampirism_integrations | vampirism_integrations  | VampirismIntegrations-1.12.2-1.2.0.jar             | None                                     |
       | LCHIJA | vanillafix             | 1.0.10-150              | VanillaFix-1.0.10-150.jar                          | None                                     |
       | LCHIJA | wizardry               | 0.10.8                  | wizardry-0.10.8.jar                                | None                                     |
       | LCHIJA | zawa                   | 1.12.2-2.0.2            | zawa-1.12.2-2.0.2.jar                              | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
       | LCHIJA | structurize            | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar            | None                                     |
       | LCHIJA | minecolonies           | 1.12.2-0.11.804-RELEASE | minecolonies-1.12.2-0.11.804-RELEASE-universal.jar | None                                     |
       | LCHIJA | librarianliblate       | 4.19.2                  | librarianlib-1.12.2-4.19.2-release.jar             | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      iceandfire (iceandfire-1.8.4.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      Wizardry Plugin (wizardry-0.10.8.jar)
                                        com.teamwizardry.wizardry.asm.WizardryTransformer
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Electroblob's Wizardry (ebwizardry)

**Comment by Lavdrim18** [comment]
I hope so much that i can play again with this mod pls help me i need this mod :D

thanks for reading

**Comment by murapix** [comment]
Error calls out Electroblob's Wizardry, not us
