### ISSUE TITLE
[Mod Conflict] Incompatibility with Flux Networks

### ISSUE THREAD

**Issue by RedneckNoob** [TeamWizardry/Wizardry#321]
Despite a purported fix in December 2017, there is an incompatibility with Flux Networks. When that mod is enabled, fire and redstone recipes do not produce a product but remove the item.

Disabling the Flux Network allows for fire recipes to create products. Changing the config file for Flux Networks to allow for the old recipe only gives Flux as a result of fire recipes.

Minecraft 1.12.2, forge 14.23.5.2847
Flux Networks 1.12.2-4.0.14-32
Wizardry Mod 0.10.8

Posting to Flux Networks as well.

**Comment by murapix** [comment]
This is not an incompatibility - we here decided that if Flux Networks is installed, we will deffer the standard burning redstone recipe to them by not allowing our own to be initialized, and added a redstone block to devil dust recipe to compensate.

**Comment by Sakata-MC** [comment]
Just a heads-up, but flux networks has an alternate recipe using obsidian "smashing" redstone before this bug report was filed. So you could turn off the deferment, its not needed unless the person configs flux networks to use old recipe.
