### ISSUE TITLE
Wisdom Door Duplicating 

### ISSUE THREAD

**Issue by DerpyJakey** [TeamWizardry/Wizardry#323]
Simply breaking the Wisdom Doors will drop 2 instead of one

**Comment by murapix** [comment]
Having placed and broken wisdom doors many a time, and not seen this happen, I'm going to need more info than that - to start off, what versions of Wizardry and its dependencies are you using?

**Comment by DerpyJakey** [comment]
Huh interesting. I am using the Wizardry 0.10.8, LibrarianLib 4.20, and Forgelin 1.8.4. I am also running Forge 14.23.5.2854.

**Comment by DerpyJakey** [comment]
I did more testing and its not just down to wizardry. I apologize for the inconvenience.

**Comment by murapix** [comment]
Ah, well good luck on finding the culprit
