### ISSUE TITLE
CRash with Misty World 

### ISSUE THREAD

**Issue by Zack7292** [TeamWizardry/Wizardry#324]
Well idk what really happen i just crash and it seem to be between this mod and Misty World so yea here is the crash log: https://pastebin.com/QTsm8rwu

**Comment by PhotonChaos** [comment]
What were you doing when the game crashed?

**Comment by Zack7292** [comment]
simply generating terrain

**Comment by Zack7292** [comment]
im in a modpack so if you want i could give you a mediafire link to the indev version
if needed

**Comment by PhotonChaos** [comment]
This looks like a misty world issue, so maybe try reporting it there?

**Comment by Zack7292** [comment]
ok i'll also link this issue in the report

**Comment by Zack7292** [comment]
seem like the last release (they did it after i create this issue) fixed this issue since i've been generating for about 20 minutes without any issues :)
