### ISSUE TITLE
Magician's Worktable Missing Event Components

### ISSUE THREAD

**Issue by kreezxil** [TeamWizardry/Wizardry#328]
**Describe the bug**
When attempting to craft a spell in the Magician's Workbench, the Event Components, which allow dictation of whether the spell will exclusively effect Entities or Blocks, do not appear and are nonfunctional. They should be within the bottom left grid, underneath the grid containing the blue Shape components. Attached image relevant. Attempts to use them as if it's a simple missing texture were not fruitful. 

**To Reproduce**
1. Obtain Magician's Worktable
2. Open Magician's Worktable

**Screenshots**
![image](https://user-images.githubusercontent.com/69659665/90207277-d7f0fa00-ddb3-11ea-8f82-bb9d0fc5f65f.png)

**Versions:**
 - Minecraft: 1.12.2
 - forge-14.23.5.2854
 - World Of Dragons v21.17.274
 - Wizardry v0.10.8

Crash and debug logs N/A, reproduced by multiple players.

Originally posted at https://github.com/kreezxil/World-of-Dragons/issues/449 by one of my players for my own pack World of Dragons.

**Comment by SwissCheese5** [comment]
They were removed because they were causing nothing but confusion. You're better of not even thinking about them.
