### ISSUE TITLE
Zone -> Beam spells become unusable after one cast.

### ISSUE THREAD

**Issue by Sourpowerpete** [TeamWizardry/Wizardry#33]
https://gfycat.com/NauticalHalfBrocketdeer
You can't tell since the spell is unusable after the first cast, but I'm right clicking the entire gfy. I used a serum to show that a lack of mana wasn't the issue.

**Comment by LordSaad44** [comment]
note: cooldown bug

**Comment by LordSaad44** [comment]
Fixed.
