### ISSUE TITLE
Optifine Leaves

### ISSUE THREAD

**Issue by disastercube** [TeamWizardry/Wizardry#333]
Wisdom leaves and other types of greens are not compatible with shaders waving effect.

**Comment by murapix** [comment]
Unsupportable feature - optifine is closed source (so we have absolutely no clue what could even be done to fix this), and our leaves are pretty much standard.

**Comment by disastercube** [comment]
What about removing the "Wisdom leaves" and replace them with an already existing variations such as "Dark oak leaves". The current texture of the leaves doesn't really spell Nature, magic or vanilla. By doing so, the problem would be resolved and the trees would look a bit better (if adding a new tree variation as well).

**_Simplified example_**
![2020-10-17_19 17 01](https://user-images.githubusercontent.com/62697421/96349103-a0514780-10ad-11eb-8c55-392d91841b26.png)

**Comment by murapix** [comment]
Because they need to drop wisdom wood saplings, not vanilla saplings.

**Comment by disastercube** [comment]
You could make it so if a sapling is dropped in mana it becomes the sapling (hence the reason why wisdom trees spawn near mana pools).
Also, is there a config option to set mana pool frequency spawn rate and a way to disable wisdom tree natural spawn?

**Comment by murapix** [comment]
That's already the case, normal saplings dropped in mana become wisdom saplings. The tree is still intended to be a completely self-contained way of creating more wisdom wood, without needing any mana.

And yes, there is a config option for the mana pool frequency, but no, there is nothing to affect the tree spawns.

**Comment by disastercube** [comment]
What about just changing the leaves texture. As it is right now it doesn't really fit in the game (without shaders to make it blend more in its surroundings) and it looks like a copy from many other mods that use the same leaves texture.

**Comment by disastercube** [comment]
Also, I'm having trouble with a setting shaders provide. You can add waving to modded leaves by yourself in the shader folder - block.properties but I'm having troubles implementing it

block.<id>=<block1> 

Vanilla leaves.
block.10018 = oak_leaves spruce_leaves birch_leaves jungle_leaves acacia_leaves dark_oak_leaves

**Comment by murapix** [comment]
The block is `wizardry:wisdom_leaves` - all modded blocks have a `modid:` prefix before the actual name (there's actually a hidden `minecraft:` before all vanilla blocks too, but that's just the assumed default, so usually not specified)
