### ISSUE TITLE
Perfect Nacre Pearl crafting humanly impossible.

### ISSUE THREAD

**Issue by Delerium** [TeamWizardry/Wizardry#336]
I've used a stopwatch set to 30 seconds, and I every time I collect a pearl I keep hitting either a little underdone or a little overdone. There needs to be a bigger window for perfect pearl production, because as it is right now, I don't see a way of making them.

**Comment by SwissCheese5** [comment]
It's meant to be exclusively automated. Use an in-game redstone timer. People have done it several times.

We plan on making the gap larger in future updates, however.
