### ISSUE TITLE
Beam -> Zone -> Time Slow... teleports the player?

### ISSUE THREAD

**Issue by Sourpowerpete** [TeamWizardry/Wizardry#34]
I'm honestly not sure what's going on here.
https://gfycat.com/QuarterlyWearyCaracal
Sometimes the game also freezes up with no crash.

**Comment by LordSaad44** [comment]
can confirm..

**Comment by Darinth** [comment]
When I initially was watching the video, it looked like it was an issue with the chunk cache and it may well still be.

When the effect goes off, you'll see that A: The chunk cache drops to zero momentary, B: All of the biome/block data goes away and is replaced by "Waiting for chunk...", C: The coordinates don't appear to initially change at all.

Without the block data, the player starts to quickly fall until they fall into the void. Around the time that their Y coord hits -87, there's a single frame where they appear at 8.5, 65, 8.5 which is the part here that really confuses me, after which they teleport to the world ceiling at the coordinates they started at and fall to the ground. I suspect that the 8.5, 65, 8.5 may just be an artifact of some failsafe. In creative does minecraft now teleport you to the ceiling if you fall too far into the void?

**Comment by Demoniaque** [comment]
I have no clue man. I'm just as lost as you are.

**Comment by ouroborus** [comment]
Vanilla doesn't but the Cyclic mod has an item that teleports you like that if you fall into the void.

**Comment by Demoniaque** [comment]
Well I can't reproduce it anymore. So uh...
