### ISSUE TITLE
Wands not working showing as unknown item

### ISSUE THREAD

**Issue by shloakvatsyayan** [TeamWizardry/Wizardry#340]
It was showing the wand things (I think they are wands) as a pink and black square. Please fix this or if it's my computer, please help me. I'm also getting this message when loading a book: #339 . EDIT: Ignore the "#339", I saw the issue post later after posting this issue and I saw it was just a bug. EDIT2: It is no longer showing the book not loading issue.

**Comment by shloakvatsyayan** [comment]
No One has replied and this mod is now starting to get boring. Please help me.

**Comment by murapix** [comment]
Can you post both a screenshot of what you're seeing and a startup log from a time it happened? Textures not showing up isn't alone enough to tell what's going on

**Comment by shloakvatsyayan** [comment]
Ok, will do, but I'll post it tomorrow  because I'm busy today.

**Comment by shloakvatsyayan** [comment]
![2021-04-09_08 39 19](https://user-images.githubusercontent.com/67813460/114181278-51bf9000-990f-11eb-87ae-8b0e7c1a04f1.png)
![2021-04-09_08 39 25](https://user-images.githubusercontent.com/67813460/114181280-51bf9000-990f-11eb-80b0-8a088dbe4725.png)
![2021-04-09_08 39 27](https://user-images.githubusercontent.com/67813460/114181281-51bf9000-990f-11eb-828e-8f7c2551ca3b.png)
![2021-04-09_08 39 37](https://user-images.githubusercontent.com/67813460/114181282-51bf9000-990f-11eb-95d6-7a36bf5a2614.png)
![2021-04-09_08 39 43](https://user-images.githubusercontent.com/67813460/114181283-52582680-990f-11eb-86a9-d2b8d20bdc3e.png)

**Comment by murapix** [comment]
Ah, those ones not having textures. That's perfectly fine, they're incomplete blocks/items that just shouldn't have gone out in a public build

**Comment by shloakvatsyayan** [comment]
Wait but then how do you get wands??? I thought those were the wands, so then what are they?

**Comment by murapix** [comment]
You make a spell in the Magician's Worktable, put in on a nacre pearl using the Crafting Plate structure, then craft that pearl a staff - you can see the empty staff just to the left of the fairy wings.
