### ISSUE TITLE
I successfull store the spell to the nacre_pearl, but could not crafting it to the staff?

### ISSUE THREAD

**Issue by blueshadowlaser2023** [TeamWizardry/Wizardry#357]
I successfull store the spell to the nacre_pearl, but could not crafting it to the staff?
First throw the pearl ,then the empty staff , the crafting_plate is not active.
Then I first throw the empty staff, after throw the staff, I throw the spell-infused pearl.  Get an explosion, all is missing, only a empty pearl is left.

**Comment by Hadaward** [comment]
This is not the right way to create a spell, have you read the mod book?

1. You create your spell at the wizard's table
2. You need to throw a glass orb into a pool of nacre and leave it in the lake for 30 seconds to get a good pearl.
3. The recipe for the spell that you saved on the sorcerer's table should appear in your sorcerer's codex. You place these ingredients on the crafting plate and then place the pearl. As long as the mana orbs have enough, the spell will be created.
4. To infuse the spell pearl into the staff, just unite them both at the workbench and voila.
