### ISSUE TITLE
[1.12.1] Crash loading save

### ISSUE THREAD

**Issue by MokahTGS** [TeamWizardry/Wizardry#37]
Getting a crash loading a save game.  It loading fine a little bit ago, which is odd.

https://pastebin.com/5UvKEJJS

**Comment by LordSaad44** [comment]
did you throw Redstone in the world by any chance?

**Comment by MokahTGS** [comment]
Not that I know of...a chicken might have

**Comment by LordSaad44** [comment]
Did you try spawning a devil dust entity? Like with a command. In any case, I think I should have fixed the NPE

**Comment by MokahTGS** [comment]
No.  I didn't try any of that.

**Comment by LordSaad44** [comment]
Should be fixed in the next release.
