### ISSUE TITLE
Advancements crash?

### ISSUE THREAD

**Issue by SilkenStrand** [TeamWizardry/Wizardry#38]
I got the ''not a mana pool'' advancement, tried to open the tab, and it crashed.
[[Crash Report]](https://pastebin.com/2J8hHtFX)

**Comment by Fogrits** [comment]
Almost the same log as yours, I think that's a issue with the registered texture for some of the advancements

[Crash Report](https://pastebin.com/wwzh6zKv)

**Comment by LordSaad44** [comment]
None of those crashes are related to Wizardry funnily enough. Try putting Wizardry in a minecraft instance by itself and tell me if it crashes. Otherwise, it's another mod. Wizardry does NOTHING in advancements that's outside of vanilla's new Json system.

**Comment by SilkenStrand** [comment]
I can try it.
..Alright, pulled everything out of my mods folder aside from forgelin, liblib, and wizardry, made a new world, grabbed the ''You're a Wizard, Harry'' advancement, checked, and it [crashed](https://pastebin.com/KVgDXr0w).

**Comment by LordSaad44** [comment]
Hopefully fixed.
