### ISSUE TITLE
Exception in server tick loop (Solution contains uncountable numbers)

### ISSUE THREAD

**Issue by Zer0Lyfe** [TeamWizardry/Wizardry#39]
when I use this mod it crashes with the message above.
But stops when I remove the mod.
it might be incompatible with IC2

[Pastebin](https://pastebin.com/2Zf4tBM0)

**Comment by LordSaad44** [comment]
This crash has nothing to do with Wizardry...

**Comment by NillerMedDild** [comment]
Although the crash has nothing to do with Wizardry, it only occurs when Wizardry and LibrarianLib are added to a pack with IC2. So there must be some connection, no?

**Comment by LordSaad44** [comment]
I recommend reporting this over to ic2. If I'm reading this right, it's an issue with wind calculation?

See what they have to say about the underworld world and come back here please.

**Comment by NillerMedDild** [comment]
It has been reported to IC2:
https://bt.industrial-craft.net/view.php?id=2264#c5452

**Comment by Chocohead** [comment]
The wind sim calculations only rely on `World#getHeight` and `WorldProvider#getAverageGroundLevel`, the rest is fixed calculations. So if either one of those returned something weird (or weird relative to the other if not out right) it could break it.

**Comment by LordSaad44** [comment]
Well there's these two:
`	@Override
	public int getHeight() {
		return 0;
	}

	@Override
	public int getAverageGroundLevel() {
		return 0;
	}`
Everything is normal. Ic2's going into a problem with 0 values.
I'm going to change getHeight to 256 so it's normal. We'll see if that breaks still in the next release. Sound good?

**Comment by LordSaad44** [comment]
Gonna close this issue. If it occurs again, make a new issue.
