### ISSUE TITLE
[1.12.1] The Underworld is all kinds of hecked up

### ISSUE THREAD

**Issue by nnystyxx** [TeamWizardry/Wizardry#40]
This issue covers **three bugs:**
1: When entering the Underworld _in Survival mode_, the player dies from fall damage. 
2: When entering the Underworld _with COFH World and the Thermal mods installed_, the game crashes.
3: When entering the Underworld _with Dynamic Surroundings installed_, the console is flooded and the game lags (more on that later)

**BUG  1: FALL DAMAGE**
Problem: Falling into the Underworld kills you. It shouldn't.
Reproduction: Enter the Underworld (I'm not posting it here unless the devs give the A-OK). Notice that your legs have exploded and you are dead. Respawn in overworld.

**"BUG" 2: COFH WORLD BEING TERRIBLE**
Problem: Entering the Underworld causes the game to crash with [this report](https://hastebin.com/wogebeximu.css).
Reproduction: Do everything you just did (broken bones optional) with COFH World installed. 

**BUG 3: DYNAMIC SURROUNDINGS ALSO BEING TERRIBLE**
Problem: Entering the Underworld causes Dynamic Surroundings to print [this message](https://hastebin.com/isibucahon.pas) in the console repeatedly. This process may or may not cause a nominal amount of game lag as the sound engine tries and fails to reconcile the biome info.
Reproduction: figure it out lmao

**Comment by nnystyxx** [comment]
The fall damage thing MIGHT already be fixed.

**Comment by LordSaad44** [comment]
Everything should be fixed in the next release hopefully.
