### ISSUE TITLE
Spell balance (touch -> break)

### ISSUE THREAD

**Issue by Nocty201** [TeamWizardry/Wizardry#45]
Compared to AM2, touch/break seems woefully bad.

No modifiers, I couldn't break stone or wood, but sand/dirt did.

I threw in x8 potency, and could beak stone but stopped testing not long after.

AM2's three tiers were roughly equivalent to wood (or stone) pick, iron pick, and (I think) diamond pick.

It was also as instant as you could click (burnout aside).

**Comment by Demoniaque** [comment]
No longer relevant.
