### ISSUE TITLE
Modifiers in spells vanish if you don't follow the recipe?

### ISSUE THREAD

**Issue by Nocty201** [TeamWizardry/Wizardry#46]
Steps:

Write up touch -> dig + potency x8

Make spell, toss in 64 Prismarine crystal instead of only 8.

Final pearl had no potency in it, couldn't break stone (previous Px8 did).

**Comment by Nocty201** [comment]
projectile -> hit entity -> levitate + potency x8

No indication on the pearl potency works.

Hitting a pig with the projectile causes it to move half a block upwards?

**Comment by Nocty201** [comment]
doing a **/wizardary reset** seems to have fixed it.

**Comment by Nocty201** [comment]
And tossing in more potency items (prismarine) does count; the spell called for 8, I added 64, and it registered 64

**Comment by murapix** [comment]
There was both a bug in spell creation making modifiers only be added once, and a big change in how modifiers determine the modifications they'll add. Doing **/wizardry reset** fixes the second part, while the first is fixed just by updating to v0.3 or beyond.
