### ISSUE TITLE
Mana pools arent generating on servers, even with the config turned to 1 in 8

### ISSUE THREAD

**Issue by baggatbt** [TeamWizardry/Wizardry#47]
I flew around for 2000 or so blocks looking for pools but they don't seem to be generating.

**Comment by murapix** [comment]
They generate underground the majority of the time - it makes them seem very rare, but they are in fact extremely common.

That said, mana pool generation is definitely not complete yet. The config doesn't affect it yet (it's just set to max chance atm), and while it does feel nice to find underground pools of mana, surface pools shouldn't be suffering because of it. It at least is already on the list of things to fix.

**Comment by drakray** [comment]
Are Mana Pools generation tied to the vanilla LakeGen? cause I use a custom gen which disable Vanilla Water and Lava lake(but allow other like BoP Poison/Quicksand), and I can't find yours
I used Minutor with a Modded.json adapted to make the liquid stand out, and couldn't find any in many thousand of block of travel, under or over ground
That in SSP

**Comment by murapix** [comment]
It should have nothing to do with vanilla lake gen, it's just a standalone world generator added to the top of the world generation list. First of all, what version are you using? If it's on the latest version, what rarity does the config have for the pools? Finally, could you show what you're seeing with Minutor (and what it looks like if it's making something stand out), or if not, clear out all the stone in a large area with something like WorldStripper?

**Comment by drakray** [comment]
wizardry 0.41
mana_pool_rarity=25
for Minutor, I got the fluid block ID by placing some in Creative, and used config to make it black(000000), with everything else in pink(ff00ff), then looked through each Y level on large scale, can't realy post hundreds of layered screenshot lol

**Comment by murapix** [comment]
Hmm... I'll have to ask around. I had someone else ask me if the mana liquid had been removed, because he didn't see any pools anywhere, so there might be something going on with the config that's keeping it from working outside the dev environment.

**Comment by drakray** [comment]
Could it be a conflic with The Lost Cities config generateLakes=false?
It doesnt stop BoP from generating though

**Comment by murapix** [comment]
I just tested it, a world with just Wizardry, and did come across a mana pool (although it did take a bit of searching).

![image](https://user-images.githubusercontent.com/12856095/32531105-e5a9ae00-c3f6-11e7-971b-413377319525.png)

It might be another mod somehow disabling it, or you could just be insanely unlucky here. Looking at the Lost Cities code, it doesn't look like that config could possibly affect mana pool generation.

**Comment by drakray** [comment]
Ill make some test later then, thanks

**Comment by drakray** [comment]
Couple of test with 0.42, got some in Normal Gen, got nothing in Superflat "Overworld", very rare in Quark Realistic(more common around Y~45), BiomesOPlenty got me nothing either
It should be noted that my Lost Cities map was using the BOP connector, though it does not explain the superflat setting

**Comment by murapix** [comment]
I've revamped the mana pool generation, so it now doesn't care about world type (will work for BoP and Lost Cities worlds, not just vanilla generation), and is assured to generate on the surface. Will be out with the next update.
