### ISSUE TITLE
[Suggestion] Add a liquid mana recipe for skyblocks or premade worlds.

### ISSUE THREAD

**Issue by MokahTGS** [TeamWizardry/Wizardry#49]
I'm playing on a premade world and so mana pools are not generating naturally.  I would suggest adding a way to make mana buckets by crafting a water bucket with other vanilla objects.  In a modpack with ExNihilo I would just add a water transform with the crucible but it would probably serve you best to add a way to get liquid mana without other mods making this compatible with many different game modes.

**Comment by murapix** [comment]
[CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker)
