### ISSUE TITLE
[1.12.2] Rendering Issue

### ISSUE THREAD

**Issue by MasterEnderman** [TeamWizardry/Wizardry#51]
After updating to the 0.4 the player skin is rendered in a strange way. Got the 0.3 again and everything is fine.

Forge: 14.23.0.2529
Wizardry: 0.4
Ingame: https://imgur.com/kfdcyUc

**Comment by Demoniaque** [comment]
Can you reproduce this with wizadry alone? (with liblib and forgelin of course)

**Comment by Demoniaque** [comment]
Also paste your whole log in a hastebin please

**Comment by MasterEnderman** [comment]
I can't reproduce it with only the mods + requirements.

Here is the log (to big for pastebin): https://gist.github.com/MasterEnderman/c0da2a308068ee37cb15c86b3b0d4d9e

**Comment by Demoniaque** [comment]
Wrong log file.

**Comment by Demoniaque** [comment]
This issue apparently happens when wizardry is with custom main menu, someone please confirm

**Comment by Jizanthapus** [comment]
Can confirm.
I started seeing this after updating from Wizardry v0.3. Have tested through Wizardry v0.42.
With Custom Main Menu enabled [here are the issues I am seeing.](https://imgur.com/a/Hwedu)
Everything is fine with either Wizardry or CMM disabled. 
[Here](https://gist.github.com/Jizanthapus/9633cc45f2bf4c5fb464a648814c33aa) is my current mod list.

**Comment by MasterEnderman** [comment]
I'm using Custom Main Menu as well.

**Comment by Demoniaque** [comment]
Fixed. :) Will be in the next update
