### ISSUE TITLE
Crash on Linux server, forge 2531

### ISSUE THREAD

**Issue by drakray** [TeamWizardry/Wizardry#54]
https://pastebin.com/PjWVDr3i
MC 1.12.2
Forge 2531
Wizardry 0.41
Librarianlib 1.4
Forgelin 1.5.1
Bunch of other mods, bunch of jvm argument, all in the file

Crash on creating new server, I don't think I even got to generating anything

**Comment by murapix** [comment]
Ah yes, this has been found and fixed in dev, and will be out with the next update.

**Comment by drakray** [comment]
any ETA for this fix?

**Comment by murapix** [comment]
I've asked Saad to make, test, and post another build, since there are a couple issues on my end keeping me from running it. It should be out within a couple days, depending on his schedule.

**Comment by Demoniaque** [comment]
On it.
