### ISSUE TITLE
Manual GUI Scaling and Auto GUI Scaling of book don't line up

### ISSUE THREAD

**Issue by GazbonicAcid** [TeamWizardry/Wizardry#55]
This is all with MC Maximized.
When GUI Scale set to auto, book gui relatively same size as normal MC GUI when GUI Scale set to Normal.
When GUI Scale set to normal, book about as large as normal MC GUI when GUI Scale set to Auto.
This makes the book un-navigatable when my Minecraft is maximized and GUI Scale manually set to Normal.
But same maximization/resolution set to Auto and the book is easy to navigate,
but MC gui is too big now.
I usually manually set gui scale to normal when I play Minecraft because Auto makes the Minecraft gui too big when my Minecraft is maximized.
However when my Minecraft is maximized, your book is only navigatable with GUI Scale set to auto.
And when set to Normal it's far too large.
This is not how vanilla GUI Scaling works as seen in my screenshots.
[screenshots of GUI Scale set to Auto](https://imgur.com/a/Gb3HA)
[screenshots of GUI Scale manually set to Normal](https://imgur.com/a/ZJRaG)
[Screenshot of the mods I use](https://imgur.com/VGbBPFF)
[zipped up Instance logs](https://github.com/TeamWizardry/Wizardry/files/1455553/logs.zip)

**Comment by thecodewarrior** [comment]
This is probably because @saad makes enormous GUIs, and so there is an auto-scaling system in LibLib to make it fit even when the GUI scale is set larger. The system is finicky, so it may need to be changed.

I’m away from my computer at the moment, so if you can upload the screenshots to imgur I can start figuring out what the problem might be now, or if not it’ll have to wait a couple days till I get home and can unzip the file.

**Comment by GazbonicAcid** [comment]
Done.
[screenshots of GUI Scale set to Auto](https://imgur.com/a/Gb3HA)
[screenshots of GUI Scale manually set to Normal](https://imgur.com/a/ZJRaG)
[Screenshot of the mods I use](https://imgur.com/VGbBPFF)
P.S. I also updated the original post to use the imgur links.

**Comment by thecodewarrior** [comment]
Sorry about the delay. I have an idea of what may be happening. I think the code may erroneously be scaling the GUI _up_ beyond the default scale, which it should never do.

**Comment by Demoniaque** [comment]
@thecodewarrior can this be marked as fixed?

**Comment by Demoniaque** [comment]
This will be fixed in 1.13 unfortunately. Unsolvable otherwise with the current system.
