### ISSUE TITLE
Crash loading server

### ISSUE THREAD

**Issue by Jizanthapus** [TeamWizardry/Wizardry#57]
Player was dropping a nacre pearl into a liquid mana pool when the server crashed. Now, the server crashes immediately after it loads the world file. 

[Crash log (Description: Exception in server tick loop)](https://gist.github.com/Jizanthapus/adcfbd1fa43aa98d94da8e1cf63c67a6)

**Comment by Demoniaque** [comment]
God damn. particle spawning on the server. I'll hopefully have enough time to fix it tomorrow.

**Comment by Demoniaque** [comment]
Fixed.
