### ISSUE TITLE
strukture problem

### ISSUE THREAD

**Issue by MoonlightShad0w** [TeamWizardry/Wizardry#63]
my problem in the news version are the struktures i realy don´t know why it is not working ( both of them)
 can anyone help me please

**Comment by Demoniaque** [comment]
Provide more information/images.

**Comment by MoonlightShad0w** [comment]
![2017-11-26_19 54 58](https://user-images.githubusercontent.com/32490703/33243303-d345b8c0-d2e3-11e7-9f61-c9e0f96013f9.png)
![2017-11-26_19 55 03](https://user-images.githubusercontent.com/32490703/33243304-d360cd18-d2e3-11e7-9d15-39cfecbaa695.png)
![2017-11-26_19 55 11](https://user-images.githubusercontent.com/32490703/33243305-d37a835c-d2e3-11e7-8407-5bfcc36c8733.png)
![2017-11-26_19 55 17](https://user-images.githubusercontent.com/32490703/33243306-d39423ac-d2e3-11e7-992c-6a1045bf4ffc.png)

some images hope it helps.

**Comment by murapix** [comment]
That's a glitch in the book, which has already been fixed for the next update. The stone slabs on the crafting altar structure are actually supposed to be quartz slabs.

**Comment by MoonlightShad0w** [comment]
don´t work 
![2017-11-26_20 14 28](https://user-images.githubusercontent.com/32490703/33243437-7e45e630-d2e6-11e7-9d73-03eed637a606.png)

**Comment by Demoniaque** [comment]
Looks fine to me. Try crafting something.

**Comment by MoonlightShad0w** [comment]
i can´t craft some by the way wenn you render the structure (the mana batery) the stairs are bugy
the stairs in the rendering are note conectet in ther corner
![2017-11-26_21 32 03](https://user-images.githubusercontent.com/32490703/33244088-4c1d43be-d2f1-11e7-89b0-b7204c48a8f1.png)

**Comment by Demoniaque** [comment]
The rendering is fine, place them as the are.

**Comment by MoonlightShad0w** [comment]
sorry it don´t work i wait for the next update

**Comment by Demoniaque** [comment]
It works for everyone else. youre doing something wrong.
