### ISSUE TITLE
Psi / Wizardry interface glitch.

### ISSUE THREAD

**Issue by Math321** [TeamWizardry/Wizardry#64]
If you are holding a Psi item (a CAD or a Psimetal item) that can contain spells, AND that Psi item DOES have a spell selected, then part of Wizardry's Magician's Worktable interface goes transparent.

This does not happen if the Psi item has an empty spell slot selected, OR if the Psi item is either a piece of Psi's armor or the exosuit controller.

Normal interface: https://prnt.sc/himt01
Bugged interface: https://prnt.sc/himtrm

You can still hover over spell-part icons to see them though: https://prnt.sc/himtzc

**Comment by Demoniaque** [comment]
sounds like psi is messing with z index on the screen? report this to psi please.

**Comment by Demoniaque** [comment]
Please paste your whole log (in pastebin or hastebin) because you failed to do that. Otherwise I'll be closing the issue.

**Comment by Demoniaque** [comment]
This is one edge case that's staying unresolved.
