### ISSUE TITLE
High CPU time from RedstoneBluetooth.tick()

### ISSUE THREAD

**Issue by OrdinatorStouff** [TeamWizardry/Wizardry#65]
On official ATM3 server when profiling with VisualVM when TPS is low (<10) we are seeing high percentages for `com.teamwizardry.wizardry.api.item.RedstoneTracker$RedstoneBluetooth.tick()` in both onPostWorldTick **and** onPreWorldTick. In both places it's looking like ~15% CPU time each on the server thread when we're already over 100ms per tick.

The first issue I'd think is seeing if this is needed to be called in on both pre and post tick events ("double dipping?") and secondly see if it can be optimized to not be so resource intensive. VisualVM snapshot/sample attached

Server/Modpack is running:
All The Mods 3 v 5.2
Forge 2256
wizardry-0.5.1.jar

[snapshot-1512409453564.zip](https://github.com/TeamWizardry/Wizardry/files/1528220/snapshot-1512409453564.zip)

**Comment by Demoniaque** [comment]
Noted. Thank you for the thorough report. Where you crafting devil dust while testing the cpu or was this consistent the whole time?

**Comment by OrdinatorStouff** [comment]
This has been consistent, with higher numbers the longer the server has been up since last restart. Very few players have looked into starting Wizardry on our server yet so there should be very little to no Wizardry content active at any given time. This profile sample attached is an average from a period over many minutes (I forgot to time it but maybe 5 to 10 minutes long) and none of the ~5 active players were crafting devil dust.

**Comment by Demoniaque** [comment]
Ok. The issue is wizardry running tons of blockstate calls every tick around redstone items (and all blocks around them). run a kill command to kill all redstone items in the world to temporarily fix the issue until the next release is out. Thank you, I'll be heavily reducing all the calls.

**Comment by OrdinatorStouff** [comment]
Awesome, Thank you for the prompt follow-up!

**Comment by OrdinatorStouff** [comment]
I know you've already said you're addressing this I just wanted to ask / mention one other thing. The CPU time for these calls starts low on a new server start, then rises over time, but killing item entities doesn't bring the total down, it just keeps climbing until restart.

This made me wonder if the internal lists to handle the redstone entities aren't being 'emptied' of items after the respective entities leave the world. I looked around in the code and didn't seem to see anywhere that they would be removed from the list but I also would not consider myself a dev to be knowledgeable on such things. Just something else to maybe double check if you're so inclined.

**Comment by Demoniaque** [comment]
Thanks for pointing that out and sorry for only reading this now.

**Comment by OrdinatorStouff** [comment]
@Demoniaque -- I should have made a new issue, I know how easy it is for comments to go unnoticed on already-closed tickets. I also apologize for not following up sooner, I had been working on collecting some comparison sampler reports to show over time the usage goes up but I admit I hadn't prioritized mentioning it until I had clear enough, useful evidence (as opposed to **only** speculation/assumptions like I discuss below).

If this is still useful, the attached zip has two sampler export. The total sample time was about 7 minutes long for each one. One was started a few minutes after server started and a few players had logged back in. The RedstoneBluetooth was at like under 2% total. The second snapshot was from the same "boot" (the server had not been stopped) but after about 130 minutes of uptime. That report showed over 10% for RedstoneBluetooth.

[wizardry_snapshots_atm3.zip](https://github.com/TeamWizardry/Wizardry/files/1591763/wizardry_snapshots_atm3.zip)

This next part is purely speculation and is only meant to provide an insight to what I assume based on administrating a semi-public atm3 server with wizardry:

It seems like the devil dust crafting mechanism overall is more of an impact than necessary. A baseline of even ~2% of cpu time for a fairly simple crafting mechanic is high. Every mechanism tile in the entire ticking world only gets up to ~5% sometimes, by comparison, and every little bit matters when chasing TPS when it's already over 50ms/tick on server start.

It seems like devil dust has a "leak" -- my inexperienced eyes did not see a way for redstone item entities to be removed from the list even after the entity became `Nothing` the list still seemed like it would have persisted the entry/pointer/whatever

It seems like this might be affecting all worlds, even worlds with no loaded chunks whatsoever. Just like we see CPU profiling time "creep up" on redstone bluetooth, we also see *empty* dimensions slowly climb into multiple milliseconds per tick even with 0 loaded chunks.

**Comment by Demoniaque** [comment]
Yes all i need to do is purge the array list. Will be in the next update.

**Comment by xorinzor** [comment]
any ETA on the update for this? It has a pretty significant impact so far, requiring me to restart the server every few hours rather then once every 12.

**Comment by murapix** [comment]
I've replaced the whole system in-dev (2afddba031f6d9cffef7421d1698a76fb195640f and e0bafc4309b4f0bc9af4e56c7d402b6de116c27b) which has replaced the fire stuff with a modified version of Flux Network's fire crafting system (along with converting both fire and mana crafting to JSON recipes - the mana crafting will need profiling). We've got a bit more bugfixing to do before getting out an update for all this, but it should be soon.

**Comment by murapix** [comment]
Just got the update out, now that our ASM seems to finally be working right.
