### ISSUE TITLE
Suggestion: don't use tick event for version checker

### ISSUE THREAD

**Issue by OrdinatorStouff** [TeamWizardry/Wizardry#67]
https://github.com/TeamWizardry/Wizardry/blob/7464569d7ed9cdcb73199268a3d359f61fea9a37/src/main/java/com/teamwizardry/wizardry/common/core/version/VersionChecker.java#L32

I understand that the majority of the code block is skipped with `if !true` using the `triedToWarnPlayer` variable but I assume that it's still highly unnecessary to have this class being called every client tick.

Possible suggestions could be using another event like onWorldJoin that only is fired once per dimension join/change and/or maybe adding in code to unregister this from the event after it's executed once.

**Comment by Demoniaque** [comment]
Botania uses this exact system. It's staying as it literally has 0 performance issues.

**Comment by OrdinatorStouff** [comment]
I have no evidence to support that it has any performance issues either, so if it's known to be safe then I suppose it doesn't matter. I had just noticed it and it seemed excessive and wanted to bring it up just in case.
