### ISSUE TITLE
Crash on launch on the 0.6.1

### ISSUE THREAD

**Issue by vrork** [TeamWizardry/Wizardry#69]
https://pastebin.com/rMtZ5RY0

I am using the latest forge version and i have deleted both the wizardry in the config files (both the txt one and the folder)

**Comment by Demoniaque** [comment]
Update liblib.

**Comment by vrork** [comment]
The updated of it only appeared after i posted the crash. Maybe make a reminder on the changelog to update it?

**Comment by Demoniaque** [comment]
No. This should be common sense. Sorry.
