### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by darkphan** [TeamWizardry/Wizardry#70]
Minecraft: 1.12.2
Wizardy Version: 0.6.1
LibrarianLib Version: 4.3

Crashlog: https://pste.me/#/CKOub

**Comment by R-ZERO** [comment]
Same

**Comment by dmodoomsirius** [comment]
https://gist.github.com/dmodoomsirius/661c0e9f8a4283536d4550b8c7c574d5
Minecraft: 1.12.2
Wizardy Version: 0.6.1
LibrarianLib Version: 4.0

**Comment by Demoniaque** [comment]
Trying to fix it.

**Comment by Demoniaque** [comment]
Fixed. Will be in the next update.
