### ISSUE TITLE
Touch = Caster?

### ISSUE THREAD

**Issue by Zsashas** [TeamWizardry/Wizardry#72]
![2017-12-13_00 57 22](https://user-images.githubusercontent.com/6917535/33930093-a40ebe70-dfa0-11e7-8b36-3ac8302540ba.png)
![2017-12-13_00 57 23](https://user-images.githubusercontent.com/6917535/33930094-a425d088-dfa0-11e7-80f6-2e359c4e024a.png)

**Comment by Demoniaque** [comment]
woopsies.
