### ISSUE TITLE
[1.12.2] [0.6.2] - Mana Battery Crash

### ISSUE THREAD

**Issue by Alaberti** [TeamWizardry/Wizardry#75]
https://pastebin.com/K8FBdWa9

I don't even.

**Comment by Alaberti** [comment]
Think this issue could cause bauble rings to vanish?

**Comment by Math321** [comment]
Context for above: One of our players reported their Botania rings went missing after a crash, but they were unsure which crash did it - they gave us two crashlogs, this one and an unrelated one.

**Comment by Demoniaque** [comment]
This is not a wizardry problem. The log does not mention wizardry nor the mana battery nor does wizardry interact in any way with botania's baubles.

**Comment by Alaberti** [comment]
That is because I linked the incorrect log: https://pastebin.com/QYTif2yi

**Comment by Demoniaque** [comment]
Hopefully fixed. Shouldn't render the mana battery if it's model isn't rendering now.
