### ISSUE TITLE
Crafting altar's outer slabs can be stone slabs, but won't consider it incorrect and spawn red dots

### ISSUE THREAD

**Issue by Chocobro** [TeamWizardry/Wizardry#76]
Created a crafting altar when on Wizardry v0.6.0, on All The Mods 3 v.5.3. Updated to W v0.6.2 (most recent) and ATM3 v.5.5 (most recent), and the altar didn't work. Discovered that it was due to the very outer slabs being stone slabs (remnants of v0.6.0), instead of quartz slabs.
Talked with Demoniaque in discord to debug, and found this bug despite thinking it was a different bug.

Despite the outer slabs being stone, the multiblock wouldn't try to correct it by placing phantom red dots in their place.
Bug seems to happen with all slabs. The multiblock sees them as just slabs, instead of sandstone or stone or wood slabs. Tested with all three of those mentioned, as well as quartz slabs. Altar only worked with the correct one, quartz.

**Comment by Demoniaque** [comment]
Crafting altar didn't render error blocks at all. Fixed.
