### ISSUE TITLE
Achievements misconfigured

### ISSUE THREAD

**Issue by ouroborus** [TeamWizardry/Wizardry#78]
The two achievements relating to bedrock and demon dust are reversed.

The achievement category tab is named named "Not a Mana Pool" rather than "Wizardry".

Wizardry 0.6.2

![2017-12-21_19 03 57](https://user-images.githubusercontent.com/392047/34283683-0cdba296-e682-11e7-960d-7d486520ff26.png)
![2017-12-21_19 04 00](https://user-images.githubusercontent.com/392047/34283684-0cee7e7a-e682-11e7-8bd5-f715398e27f7.png)
![2017-12-21_19 06 09](https://user-images.githubusercontent.com/392047/34283686-0d0199ce-e682-11e7-9a7c-c3dca9d539ae.png)

**Comment by Demoniaque** [comment]
Fixed.
