### ISSUE TITLE
Not gaining any mana?

### ISSUE THREAD

**Issue by izShelby** [TeamWizardry/Wizardry#81]
I cannot, for the life of me, figure out how I'm supposed to gain mana to cast my spells. I have built a functioning mana battery construct and have crafted the basic self -> leap wand to test it. I've been wearing the cape and crude halo for the last five hours, yet my mana bar is still completely empty and my staff just produces the particle effect. I read in the book that you could also use the power from the mana battery directly, so I put down a mana magnet and a nacre pearl on a pearl holder, yet still no dice.

Is there something I'm not seeing here?

(Amazing mod btw, excited to see where it goes.)

**Comment by Demoniaque** [comment]
Craft a mana syringe and hold down right click.
🎉

**Comment by izShelby** [comment]
Not to be obnoxious here, but maybe that should be included in the book.
