### ISSUE TITLE
Mod compatibility with Fluxnetwork

### ISSUE THREAD

**Issue by tigerdan2** [TeamWizardry/Wizardry#82]
Wizardry and Fluxnetwork both have a recepie that involves tossing a piece of redstone into lava
-> when Wizardry is installed you can not use Fluxnetwork

Possible fix:
Make it so that you need to be in the nether , if  you want to get devil dust
would kinda make sense

**Comment by Demoniaque** [comment]
I'll make an issue on flux network

**Comment by Demoniaque** [comment]
flux networks fixed it.

**Comment by murapix** [comment]
Next version will have JSON recipes for fire stuff, and a config related to them, so this interaction will be disable-able on our end too.
