### ISSUE TITLE
Mana bar is graphically updating properly.

### ISSUE THREAD

**Issue by Sourpowerpete** [TeamWizardry/Wizardry#93]
The mana bar doesn't seem to be graphically detracted from. Using spells still uses mana, but the bar still appears full.

**Comment by Demoniaque** [comment]
which halo is this?

**Comment by Sourpowerpete** [comment]
Standard (not the crappy or creative one).

**Comment by Boundarybreaker** [comment]
This happens with the crude halo as well, from what I've seen. Removing and replacing a halo makes it update again; casting a spell with the halo on makes the mana/overheat bars freeze. It might be something with spellcasting.

**Comment by Demoniaque** [comment]
Fixed.
