### ISSUE TITLE
Graphical glitches with shaders

### ISSUE THREAD

**Issue by TitusArmillius** [TeamWizardry/Wizardry#94]
In this album: https://imgur.com/a/z8Q6o... 

...you will see that the magician's worktable is the only 3D model which is experiencing graphical issues with shader mods. Specifically, it is showing reflection characteristics similar to that of water or stained glass; which leads me to presume its model/blockstate file is slightly different than that of the other objects.

Is it possible to fix this?

**Comment by Demoniaque** [comment]
Particle shaders are fixed, but the table is just a json model.
