### ISSUE TITLE
Recipe errors when starting server.

### ISSUE THREAD

**Issue by Astharok** [TeamWizardry/Wizardry#97]
I have the folowing errors while starting server. This not affect the game. And mod is still playable.

Minecraft version: 1.12.2
Wizardry version: 0.7.2
Forge version: 14.23.1.2587
Error log: https://hastebin.com/utonosekak.vbs

**Comment by murapix** [comment]
Yes, those are intended at the moment. We'd created the items you see missing here, and the recipes to make them, for the 0.7 update, but our texture artist wasn't able to make them before we needed to update. We decided to keep the items from loading until then, but didn't want to lose the recipes, so we left those errors in for the time being.

Leaving this open for others to see, and will close as soon as we get textures for those items.
