### ISSUE TITLE
Spell Names

### ISSUE THREAD

**Issue by Astebrooke** [TeamWizardry/Wizardry#98]
![2018-01-25_16 29 28](https://user-images.githubusercontent.com/35822449/35419732-75b169fe-01ee-11e8-8ea3-2bd4bac69049.png)

According to Escapee in the Discord chat, the spell names get garbled when using conditional components.

An idea to prevent that, aside from (and far cooler than) fixing the display issue caused by them, is to add a "Spell Name" GUI component to the Magician's Worktable so the spell comes out using the name you want instead of a name made up of its components.  The creation of the imbued Nacre Pearl could also reference the currently stored spell recipe's name for renaming the pearl, to avoid obnoxiously long component-based names such as "Projectile > On Block Collision > Reinforcements" instead of "Call the Horde"

I'm also opening a second issue, on recommendation, for a couple suggestions to store multiple spells.  If that gets approved and worked on the nacre pearl could take the name of the "active" spell recipe.

**Comment by Demoniaque** [comment]
Fixed in 0.8+

**Comment by Demoniaque** [comment]
(naming will be considered/added in the future)
